/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AgentSandboxRevisionLister helps list AgentSandboxRevisions.
// All objects returned here must be treated as read-only.
type AgentSandboxRevisionLister interface {
	// List lists all AgentSandboxRevisions in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.AgentSandboxRevision, err error)
	// AgentSandboxRevisions returns an object that can list and get AgentSandboxRevisions.
	AgentSandboxRevisions(namespace string) AgentSandboxRevisionNamespaceLister
	AgentSandboxRevisionListerExpansion
}

// agentSandboxRevisionLister implements the AgentSandboxRevisionLister interface.
type agentSandboxRevisionLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.AgentSandboxRevision]
}

// NewAgentSandboxRevisionLister returns a new AgentSandboxRevisionLister.
func NewAgentSandboxRevisionLister(indexer cache.Indexer) AgentSandboxRevisionLister {
	return &agentSandboxRevisionLister{listers.New[*clrkv1alpha1.AgentSandboxRevision](indexer, clrkv1alpha1.Resource("agentsandboxrevision"))}
}

// AgentSandboxRevisions returns an object that can list and get AgentSandboxRevisions.
func (s *agentSandboxRevisionLister) AgentSandboxRevisions(namespace string) AgentSandboxRevisionNamespaceLister {
	return agentSandboxRevisionNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.AgentSandboxRevision](s.ResourceIndexer, namespace)}
}

// AgentSandboxRevisionNamespaceLister helps list and get AgentSandboxRevisions.
// All objects returned here must be treated as read-only.
type AgentSandboxRevisionNamespaceLister interface {
	// List lists all AgentSandboxRevisions in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.AgentSandboxRevision, err error)
	// Get retrieves the AgentSandboxRevision from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.AgentSandboxRevision, error)
	AgentSandboxRevisionNamespaceListerExpansion
}

// agentSandboxRevisionNamespaceLister implements the AgentSandboxRevisionNamespaceLister
// interface.
type agentSandboxRevisionNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.AgentSandboxRevision]
}
