/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AgentSandboxRevisionLister helps list AgentSandboxRevisions.
// All objects returned here must be treated as read-only.
type AgentSandboxRevisionLister interface {
	// List lists all AgentSandboxRevisions in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.AgentSandboxRevision, err error)
	// AgentSandboxRevisions returns an object that can list and get AgentSandboxRevisions.
	AgentSandboxRevisions(namespace string) AgentSandboxRevisionNamespaceLister
	AgentSandboxRevisionListerExpansion
}

// agentSandboxRevisionLister implements the AgentSandboxRevisionLister interface.
type agentSandboxRevisionLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.AgentSandboxRevision]
}

// NewAgentSandboxRevisionLister returns a new AgentSandboxRevisionLister.
func NewAgentSandboxRevisionLister(indexer cache.Indexer) AgentSandboxRevisionLister {
	return &agentSandboxRevisionLister{listers.New[*clrkv1alpha1.AgentSandboxRevision](indexer, clrkv1alpha1.Resource("agentsandboxrevision"))}
}

// AgentSandboxRevisions returns an object that can list and get AgentSandboxRevisions.
func (s *agentSandboxRevisionLister) AgentSandboxRevisions(namespace string) AgentSandboxRevisionNamespaceLister {
	return agentSandboxRevisionNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.AgentSandboxRevision](s.ResourceIndexer, namespace)}
}

// AgentSandboxRevisionNamespaceLister helps list and get AgentSandboxRevisions.
// All objects returned here must be treated as read-only.
type AgentSandboxRevisionNamespaceLister interface {
	// List lists all AgentSandboxRevisions in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.AgentSandboxRevision, err error)
	// Get retrieves the AgentSandboxRevision from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.AgentSandboxRevision, error)
	AgentSandboxRevisionNamespaceListerExpansion
}

// agentSandboxRevisionNamespaceLister implements the AgentSandboxRevisionNamespaceLister
// interface.
type agentSandboxRevisionNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.AgentSandboxRevision]
}
