/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AIProviderRouteLister helps list AIProviderRoutes.
// All objects returned here must be treated as read-only.
type AIProviderRouteLister interface {
	// List lists all AIProviderRoutes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.AIProviderRoute, err error)
	// AIProviderRoutes returns an object that can list and get AIProviderRoutes.
	AIProviderRoutes(namespace string) AIProviderRouteNamespaceLister
	AIProviderRouteListerExpansion
}

// aIProviderRouteLister implements the AIProviderRouteLister interface.
type aIProviderRouteLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.AIProviderRoute]
}

// NewAIProviderRouteLister returns a new AIProviderRouteLister.
func NewAIProviderRouteLister(indexer cache.Indexer) AIProviderRouteLister {
	return &aIProviderRouteLister{listers.New[*clrkv1alpha1.AIProviderRoute](indexer, clrkv1alpha1.Resource("aiproviderroute"))}
}

// AIProviderRoutes returns an object that can list and get AIProviderRoutes.
func (s *aIProviderRouteLister) AIProviderRoutes(namespace string) AIProviderRouteNamespaceLister {
	return aIProviderRouteNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.AIProviderRoute](s.ResourceIndexer, namespace)}
}

// AIProviderRouteNamespaceLister helps list and get AIProviderRoutes.
// All objects returned here must be treated as read-only.
type AIProviderRouteNamespaceLister interface {
	// List lists all AIProviderRoutes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.AIProviderRoute, err error)
	// Get retrieves the AIProviderRoute from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.AIProviderRoute, error)
	AIProviderRouteNamespaceListerExpansion
}

// aIProviderRouteNamespaceLister implements the AIProviderRouteNamespaceLister
// interface.
type aIProviderRouteNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.AIProviderRoute]
}
