/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AIProviderRouteLister helps list AIProviderRoutes.
// All objects returned here must be treated as read-only.
type AIProviderRouteLister interface {
	// List lists all AIProviderRoutes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.AIProviderRoute, err error)
	// AIProviderRoutes returns an object that can list and get AIProviderRoutes.
	AIProviderRoutes(namespace string) AIProviderRouteNamespaceLister
	AIProviderRouteListerExpansion
}

// aIProviderRouteLister implements the AIProviderRouteLister interface.
type aIProviderRouteLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.AIProviderRoute]
}

// NewAIProviderRouteLister returns a new AIProviderRouteLister.
func NewAIProviderRouteLister(indexer cache.Indexer) AIProviderRouteLister {
	return &aIProviderRouteLister{listers.New[*clrkv1alpha1.AIProviderRoute](indexer, clrkv1alpha1.Resource("aiproviderroute"))}
}

// AIProviderRoutes returns an object that can list and get AIProviderRoutes.
func (s *aIProviderRouteLister) AIProviderRoutes(namespace string) AIProviderRouteNamespaceLister {
	return aIProviderRouteNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.AIProviderRoute](s.ResourceIndexer, namespace)}
}

// AIProviderRouteNamespaceLister helps list and get AIProviderRoutes.
// All objects returned here must be treated as read-only.
type AIProviderRouteNamespaceLister interface {
	// List lists all AIProviderRoutes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.AIProviderRoute, err error)
	// Get retrieves the AIProviderRoute from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.AIProviderRoute, error)
	AIProviderRouteNamespaceListerExpansion
}

// aIProviderRouteNamespaceLister implements the AIProviderRouteNamespaceLister
// interface.
type aIProviderRouteNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.AIProviderRoute]
}
