/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// BackendLister helps list Backends.
// All objects returned here must be treated as read-only.
type BackendLister interface {
	// List lists all Backends in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.Backend, err error)
	// Backends returns an object that can list and get Backends.
	Backends(namespace string) BackendNamespaceLister
	BackendListerExpansion
}

// backendLister implements the BackendLister interface.
type backendLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.Backend]
}

// NewBackendLister returns a new BackendLister.
func NewBackendLister(indexer cache.Indexer) BackendLister {
	return &backendLister{listers.New[*clrkv1alpha1.Backend](indexer, clrkv1alpha1.Resource("backend"))}
}

// Backends returns an object that can list and get Backends.
func (s *backendLister) Backends(namespace string) BackendNamespaceLister {
	return backendNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.Backend](s.ResourceIndexer, namespace)}
}

// BackendNamespaceLister helps list and get Backends.
// All objects returned here must be treated as read-only.
type BackendNamespaceLister interface {
	// List lists all Backends in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.Backend, err error)
	// Get retrieves the Backend from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.Backend, error)
	BackendNamespaceListerExpansion
}

// backendNamespaceLister implements the BackendNamespaceLister
// interface.
type backendNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.Backend]
}
