/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CredentialInjectionPolicyLister helps list CredentialInjectionPolicies.
// All objects returned here must be treated as read-only.
type CredentialInjectionPolicyLister interface {
	// List lists all CredentialInjectionPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.CredentialInjectionPolicy, err error)
	// CredentialInjectionPolicies returns an object that can list and get CredentialInjectionPolicies.
	CredentialInjectionPolicies(namespace string) CredentialInjectionPolicyNamespaceLister
	CredentialInjectionPolicyListerExpansion
}

// credentialInjectionPolicyLister implements the CredentialInjectionPolicyLister interface.
type credentialInjectionPolicyLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.CredentialInjectionPolicy]
}

// NewCredentialInjectionPolicyLister returns a new CredentialInjectionPolicyLister.
func NewCredentialInjectionPolicyLister(indexer cache.Indexer) CredentialInjectionPolicyLister {
	return &credentialInjectionPolicyLister{listers.New[*clrkv1alpha1.CredentialInjectionPolicy](indexer, clrkv1alpha1.Resource("credentialinjectionpolicy"))}
}

// CredentialInjectionPolicies returns an object that can list and get CredentialInjectionPolicies.
func (s *credentialInjectionPolicyLister) CredentialInjectionPolicies(namespace string) CredentialInjectionPolicyNamespaceLister {
	return credentialInjectionPolicyNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.CredentialInjectionPolicy](s.ResourceIndexer, namespace)}
}

// CredentialInjectionPolicyNamespaceLister helps list and get CredentialInjectionPolicies.
// All objects returned here must be treated as read-only.
type CredentialInjectionPolicyNamespaceLister interface {
	// List lists all CredentialInjectionPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.CredentialInjectionPolicy, err error)
	// Get retrieves the CredentialInjectionPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.CredentialInjectionPolicy, error)
	CredentialInjectionPolicyNamespaceListerExpansion
}

// credentialInjectionPolicyNamespaceLister implements the CredentialInjectionPolicyNamespaceLister
// interface.
type credentialInjectionPolicyNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.CredentialInjectionPolicy]
}
