/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DaemonAgentLister helps list DaemonAgents.
// All objects returned here must be treated as read-only.
type DaemonAgentLister interface {
	// List lists all DaemonAgents in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.DaemonAgent, err error)
	// DaemonAgents returns an object that can list and get DaemonAgents.
	DaemonAgents(namespace string) DaemonAgentNamespaceLister
	DaemonAgentListerExpansion
}

// daemonAgentLister implements the DaemonAgentLister interface.
type daemonAgentLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.DaemonAgent]
}

// NewDaemonAgentLister returns a new DaemonAgentLister.
func NewDaemonAgentLister(indexer cache.Indexer) DaemonAgentLister {
	return &daemonAgentLister{listers.New[*clrkv1alpha1.DaemonAgent](indexer, clrkv1alpha1.Resource("daemonagent"))}
}

// DaemonAgents returns an object that can list and get DaemonAgents.
func (s *daemonAgentLister) DaemonAgents(namespace string) DaemonAgentNamespaceLister {
	return daemonAgentNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.DaemonAgent](s.ResourceIndexer, namespace)}
}

// DaemonAgentNamespaceLister helps list and get DaemonAgents.
// All objects returned here must be treated as read-only.
type DaemonAgentNamespaceLister interface {
	// List lists all DaemonAgents in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.DaemonAgent, err error)
	// Get retrieves the DaemonAgent from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.DaemonAgent, error)
	DaemonAgentNamespaceListerExpansion
}

// daemonAgentNamespaceLister implements the DaemonAgentNamespaceLister
// interface.
type daemonAgentNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.DaemonAgent]
}
