/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DaemonAgentLister helps list DaemonAgents.
// All objects returned here must be treated as read-only.
type DaemonAgentLister interface {
	// List lists all DaemonAgents in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.DaemonAgent, err error)
	// DaemonAgents returns an object that can list and get DaemonAgents.
	DaemonAgents(namespace string) DaemonAgentNamespaceLister
	DaemonAgentListerExpansion
}

// daemonAgentLister implements the DaemonAgentLister interface.
type daemonAgentLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.DaemonAgent]
}

// NewDaemonAgentLister returns a new DaemonAgentLister.
func NewDaemonAgentLister(indexer cache.Indexer) DaemonAgentLister {
	return &daemonAgentLister{listers.New[*clrkv1alpha1.DaemonAgent](indexer, clrkv1alpha1.Resource("daemonagent"))}
}

// DaemonAgents returns an object that can list and get DaemonAgents.
func (s *daemonAgentLister) DaemonAgents(namespace string) DaemonAgentNamespaceLister {
	return daemonAgentNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.DaemonAgent](s.ResourceIndexer, namespace)}
}

// DaemonAgentNamespaceLister helps list and get DaemonAgents.
// All objects returned here must be treated as read-only.
type DaemonAgentNamespaceLister interface {
	// List lists all DaemonAgents in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.DaemonAgent, err error)
	// Get retrieves the DaemonAgent from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.DaemonAgent, error)
	DaemonAgentNamespaceListerExpansion
}

// daemonAgentNamespaceLister implements the DaemonAgentNamespaceLister
// interface.
type daemonAgentNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.DaemonAgent]
}
