/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// EgressL4RouteLister helps list EgressL4Routes.
// All objects returned here must be treated as read-only.
type EgressL4RouteLister interface {
	// List lists all EgressL4Routes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.EgressL4Route, err error)
	// EgressL4Routes returns an object that can list and get EgressL4Routes.
	EgressL4Routes(namespace string) EgressL4RouteNamespaceLister
	EgressL4RouteListerExpansion
}

// egressL4RouteLister implements the EgressL4RouteLister interface.
type egressL4RouteLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.EgressL4Route]
}

// NewEgressL4RouteLister returns a new EgressL4RouteLister.
func NewEgressL4RouteLister(indexer cache.Indexer) EgressL4RouteLister {
	return &egressL4RouteLister{listers.New[*clrkv1alpha1.EgressL4Route](indexer, clrkv1alpha1.Resource("egressl4route"))}
}

// EgressL4Routes returns an object that can list and get EgressL4Routes.
func (s *egressL4RouteLister) EgressL4Routes(namespace string) EgressL4RouteNamespaceLister {
	return egressL4RouteNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.EgressL4Route](s.ResourceIndexer, namespace)}
}

// EgressL4RouteNamespaceLister helps list and get EgressL4Routes.
// All objects returned here must be treated as read-only.
type EgressL4RouteNamespaceLister interface {
	// List lists all EgressL4Routes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.EgressL4Route, err error)
	// Get retrieves the EgressL4Route from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.EgressL4Route, error)
	EgressL4RouteNamespaceListerExpansion
}

// egressL4RouteNamespaceLister implements the EgressL4RouteNamespaceLister
// interface.
type egressL4RouteNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.EgressL4Route]
}
