/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// EgressDenyPolicyLister helps list EgressDenyPolicies.
// All objects returned here must be treated as read-only.
type EgressDenyPolicyLister interface {
	// List lists all EgressDenyPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.EgressDenyPolicy, err error)
	// EgressDenyPolicies returns an object that can list and get EgressDenyPolicies.
	EgressDenyPolicies(namespace string) EgressDenyPolicyNamespaceLister
	EgressDenyPolicyListerExpansion
}

// egressDenyPolicyLister implements the EgressDenyPolicyLister interface.
type egressDenyPolicyLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.EgressDenyPolicy]
}

// NewEgressDenyPolicyLister returns a new EgressDenyPolicyLister.
func NewEgressDenyPolicyLister(indexer cache.Indexer) EgressDenyPolicyLister {
	return &egressDenyPolicyLister{listers.New[*clrkv1alpha1.EgressDenyPolicy](indexer, clrkv1alpha1.Resource("egressdenypolicy"))}
}

// EgressDenyPolicies returns an object that can list and get EgressDenyPolicies.
func (s *egressDenyPolicyLister) EgressDenyPolicies(namespace string) EgressDenyPolicyNamespaceLister {
	return egressDenyPolicyNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.EgressDenyPolicy](s.ResourceIndexer, namespace)}
}

// EgressDenyPolicyNamespaceLister helps list and get EgressDenyPolicies.
// All objects returned here must be treated as read-only.
type EgressDenyPolicyNamespaceLister interface {
	// List lists all EgressDenyPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.EgressDenyPolicy, err error)
	// Get retrieves the EgressDenyPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.EgressDenyPolicy, error)
	EgressDenyPolicyNamespaceListerExpansion
}

// egressDenyPolicyNamespaceLister implements the EgressDenyPolicyNamespaceLister
// interface.
type egressDenyPolicyNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.EgressDenyPolicy]
}
