/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// EgressDenyPolicyLister helps list EgressDenyPolicies.
// All objects returned here must be treated as read-only.
type EgressDenyPolicyLister interface {
	// List lists all EgressDenyPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.EgressDenyPolicy, err error)
	// EgressDenyPolicies returns an object that can list and get EgressDenyPolicies.
	EgressDenyPolicies(namespace string) EgressDenyPolicyNamespaceLister
	EgressDenyPolicyListerExpansion
}

// egressDenyPolicyLister implements the EgressDenyPolicyLister interface.
type egressDenyPolicyLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.EgressDenyPolicy]
}

// NewEgressDenyPolicyLister returns a new EgressDenyPolicyLister.
func NewEgressDenyPolicyLister(indexer cache.Indexer) EgressDenyPolicyLister {
	return &egressDenyPolicyLister{listers.New[*clrkv1alpha1.EgressDenyPolicy](indexer, clrkv1alpha1.Resource("egressdenypolicy"))}
}

// EgressDenyPolicies returns an object that can list and get EgressDenyPolicies.
func (s *egressDenyPolicyLister) EgressDenyPolicies(namespace string) EgressDenyPolicyNamespaceLister {
	return egressDenyPolicyNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.EgressDenyPolicy](s.ResourceIndexer, namespace)}
}

// EgressDenyPolicyNamespaceLister helps list and get EgressDenyPolicies.
// All objects returned here must be treated as read-only.
type EgressDenyPolicyNamespaceLister interface {
	// List lists all EgressDenyPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.EgressDenyPolicy, err error)
	// Get retrieves the EgressDenyPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.EgressDenyPolicy, error)
	EgressDenyPolicyNamespaceListerExpansion
}

// egressDenyPolicyNamespaceLister implements the EgressDenyPolicyNamespaceLister
// interface.
type egressDenyPolicyNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.EgressDenyPolicy]
}
