/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AIProviderRouteListerExpansion allows custom methods to be added to
// AIProviderRouteLister.
type AIProviderRouteListerExpansion interface{}

// AIProviderRouteNamespaceListerExpansion allows custom methods to be added to
// AIProviderRouteNamespaceLister.
type AIProviderRouteNamespaceListerExpansion interface{}

// AgentSandboxRevisionListerExpansion allows custom methods to be added to
// AgentSandboxRevisionLister.
type AgentSandboxRevisionListerExpansion interface{}

// AgentSandboxRevisionNamespaceListerExpansion allows custom methods to be added to
// AgentSandboxRevisionNamespaceLister.
type AgentSandboxRevisionNamespaceListerExpansion interface{}

// CredentialInjectionPolicyListerExpansion allows custom methods to be added to
// CredentialInjectionPolicyLister.
type CredentialInjectionPolicyListerExpansion interface{}

// CredentialInjectionPolicyNamespaceListerExpansion allows custom methods to be added to
// CredentialInjectionPolicyNamespaceLister.
type CredentialInjectionPolicyNamespaceListerExpansion interface{}

// DaemonAgentListerExpansion allows custom methods to be added to
// DaemonAgentLister.
type DaemonAgentListerExpansion interface{}

// DaemonAgentNamespaceListerExpansion allows custom methods to be added to
// DaemonAgentNamespaceLister.
type DaemonAgentNamespaceListerExpansion interface{}

// EgressDenyPolicyListerExpansion allows custom methods to be added to
// EgressDenyPolicyLister.
type EgressDenyPolicyListerExpansion interface{}

// EgressDenyPolicyNamespaceListerExpansion allows custom methods to be added to
// EgressDenyPolicyNamespaceLister.
type EgressDenyPolicyNamespaceListerExpansion interface{}

// EgressGatewayListerExpansion allows custom methods to be added to
// EgressGatewayLister.
type EgressGatewayListerExpansion interface{}

// EgressGatewayNamespaceListerExpansion allows custom methods to be added to
// EgressGatewayNamespaceLister.
type EgressGatewayNamespaceListerExpansion interface{}

// EgressL4RouteListerExpansion allows custom methods to be added to
// EgressL4RouteLister.
type EgressL4RouteListerExpansion interface{}

// EgressL4RouteNamespaceListerExpansion allows custom methods to be added to
// EgressL4RouteNamespaceLister.
type EgressL4RouteNamespaceListerExpansion interface{}

// LoggingPolicyListerExpansion allows custom methods to be added to
// LoggingPolicyLister.
type LoggingPolicyListerExpansion interface{}

// LoggingPolicyNamespaceListerExpansion allows custom methods to be added to
// LoggingPolicyNamespaceLister.
type LoggingPolicyNamespaceListerExpansion interface{}

// MCPRouteListerExpansion allows custom methods to be added to
// MCPRouteLister.
type MCPRouteListerExpansion interface{}

// MCPRouteNamespaceListerExpansion allows custom methods to be added to
// MCPRouteNamespaceLister.
type MCPRouteNamespaceListerExpansion interface{}

// RateLimitPolicyListerExpansion allows custom methods to be added to
// RateLimitPolicyLister.
type RateLimitPolicyListerExpansion interface{}

// RateLimitPolicyNamespaceListerExpansion allows custom methods to be added to
// RateLimitPolicyNamespaceLister.
type RateLimitPolicyNamespaceListerExpansion interface{}

// TaskAgentListerExpansion allows custom methods to be added to
// TaskAgentLister.
type TaskAgentListerExpansion interface{}

// TaskAgentNamespaceListerExpansion allows custom methods to be added to
// TaskAgentNamespaceLister.
type TaskAgentNamespaceListerExpansion interface{}

// WorkerPoolListerExpansion allows custom methods to be added to
// WorkerPoolLister.
type WorkerPoolListerExpansion interface{}

// WorkerPoolNamespaceListerExpansion allows custom methods to be added to
// WorkerPoolNamespaceLister.
type WorkerPoolNamespaceListerExpansion interface{}
