/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AIProviderRouteListerExpansion allows custom methods to be added to
// AIProviderRouteLister.
type AIProviderRouteListerExpansion interface{}

// AIProviderRouteNamespaceListerExpansion allows custom methods to be added to
// AIProviderRouteNamespaceLister.
type AIProviderRouteNamespaceListerExpansion interface{}

// AgentSandboxRevisionListerExpansion allows custom methods to be added to
// AgentSandboxRevisionLister.
type AgentSandboxRevisionListerExpansion interface{}

// AgentSandboxRevisionNamespaceListerExpansion allows custom methods to be added to
// AgentSandboxRevisionNamespaceLister.
type AgentSandboxRevisionNamespaceListerExpansion interface{}

// BackendListerExpansion allows custom methods to be added to
// BackendLister.
type BackendListerExpansion interface{}

// BackendNamespaceListerExpansion allows custom methods to be added to
// BackendNamespaceLister.
type BackendNamespaceListerExpansion interface{}

// CredentialInjectionPolicyListerExpansion allows custom methods to be added to
// CredentialInjectionPolicyLister.
type CredentialInjectionPolicyListerExpansion interface{}

// CredentialInjectionPolicyNamespaceListerExpansion allows custom methods to be added to
// CredentialInjectionPolicyNamespaceLister.
type CredentialInjectionPolicyNamespaceListerExpansion interface{}

// DaemonAgentListerExpansion allows custom methods to be added to
// DaemonAgentLister.
type DaemonAgentListerExpansion interface{}

// DaemonAgentNamespaceListerExpansion allows custom methods to be added to
// DaemonAgentNamespaceLister.
type DaemonAgentNamespaceListerExpansion interface{}

// EgressDenyPolicyListerExpansion allows custom methods to be added to
// EgressDenyPolicyLister.
type EgressDenyPolicyListerExpansion interface{}

// EgressDenyPolicyNamespaceListerExpansion allows custom methods to be added to
// EgressDenyPolicyNamespaceLister.
type EgressDenyPolicyNamespaceListerExpansion interface{}

// EgressGatewayListerExpansion allows custom methods to be added to
// EgressGatewayLister.
type EgressGatewayListerExpansion interface{}

// EgressGatewayNamespaceListerExpansion allows custom methods to be added to
// EgressGatewayNamespaceLister.
type EgressGatewayNamespaceListerExpansion interface{}

// EgressL4RouteListerExpansion allows custom methods to be added to
// EgressL4RouteLister.
type EgressL4RouteListerExpansion interface{}

// EgressL4RouteNamespaceListerExpansion allows custom methods to be added to
// EgressL4RouteNamespaceLister.
type EgressL4RouteNamespaceListerExpansion interface{}

// InvocationListerExpansion allows custom methods to be added to
// InvocationLister.
type InvocationListerExpansion interface{}

// InvocationNamespaceListerExpansion allows custom methods to be added to
// InvocationNamespaceLister.
type InvocationNamespaceListerExpansion interface{}

// LoggingPolicyListerExpansion allows custom methods to be added to
// LoggingPolicyLister.
type LoggingPolicyListerExpansion interface{}

// LoggingPolicyNamespaceListerExpansion allows custom methods to be added to
// LoggingPolicyNamespaceLister.
type LoggingPolicyNamespaceListerExpansion interface{}

// MCPRouteListerExpansion allows custom methods to be added to
// MCPRouteLister.
type MCPRouteListerExpansion interface{}

// MCPRouteNamespaceListerExpansion allows custom methods to be added to
// MCPRouteNamespaceLister.
type MCPRouteNamespaceListerExpansion interface{}

// RateLimitPolicyListerExpansion allows custom methods to be added to
// RateLimitPolicyLister.
type RateLimitPolicyListerExpansion interface{}

// RateLimitPolicyNamespaceListerExpansion allows custom methods to be added to
// RateLimitPolicyNamespaceLister.
type RateLimitPolicyNamespaceListerExpansion interface{}

// TaskAgentListerExpansion allows custom methods to be added to
// TaskAgentLister.
type TaskAgentListerExpansion interface{}

// TaskAgentNamespaceListerExpansion allows custom methods to be added to
// TaskAgentNamespaceLister.
type TaskAgentNamespaceListerExpansion interface{}

// WorkerPoolListerExpansion allows custom methods to be added to
// WorkerPoolLister.
type WorkerPoolListerExpansion interface{}

// WorkerPoolNamespaceListerExpansion allows custom methods to be added to
// WorkerPoolNamespaceLister.
type WorkerPoolNamespaceListerExpansion interface{}
