/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// FallbackRoutingPolicyLister helps list FallbackRoutingPolicies.
// All objects returned here must be treated as read-only.
type FallbackRoutingPolicyLister interface {
	// List lists all FallbackRoutingPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.FallbackRoutingPolicy, err error)
	// FallbackRoutingPolicies returns an object that can list and get FallbackRoutingPolicies.
	FallbackRoutingPolicies(namespace string) FallbackRoutingPolicyNamespaceLister
	FallbackRoutingPolicyListerExpansion
}

// fallbackRoutingPolicyLister implements the FallbackRoutingPolicyLister interface.
type fallbackRoutingPolicyLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.FallbackRoutingPolicy]
}

// NewFallbackRoutingPolicyLister returns a new FallbackRoutingPolicyLister.
func NewFallbackRoutingPolicyLister(indexer cache.Indexer) FallbackRoutingPolicyLister {
	return &fallbackRoutingPolicyLister{listers.New[*clrkv1alpha1.FallbackRoutingPolicy](indexer, clrkv1alpha1.Resource("fallbackroutingpolicy"))}
}

// FallbackRoutingPolicies returns an object that can list and get FallbackRoutingPolicies.
func (s *fallbackRoutingPolicyLister) FallbackRoutingPolicies(namespace string) FallbackRoutingPolicyNamespaceLister {
	return fallbackRoutingPolicyNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.FallbackRoutingPolicy](s.ResourceIndexer, namespace)}
}

// FallbackRoutingPolicyNamespaceLister helps list and get FallbackRoutingPolicies.
// All objects returned here must be treated as read-only.
type FallbackRoutingPolicyNamespaceLister interface {
	// List lists all FallbackRoutingPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.FallbackRoutingPolicy, err error)
	// Get retrieves the FallbackRoutingPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.FallbackRoutingPolicy, error)
	FallbackRoutingPolicyNamespaceListerExpansion
}

// fallbackRoutingPolicyNamespaceLister implements the FallbackRoutingPolicyNamespaceLister
// interface.
type fallbackRoutingPolicyNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.FallbackRoutingPolicy]
}
