/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// InvocationLister helps list Invocations.
// All objects returned here must be treated as read-only.
type InvocationLister interface {
	// List lists all Invocations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.Invocation, err error)
	// Invocations returns an object that can list and get Invocations.
	Invocations(namespace string) InvocationNamespaceLister
	InvocationListerExpansion
}

// invocationLister implements the InvocationLister interface.
type invocationLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.Invocation]
}

// NewInvocationLister returns a new InvocationLister.
func NewInvocationLister(indexer cache.Indexer) InvocationLister {
	return &invocationLister{listers.New[*clrkv1alpha1.Invocation](indexer, clrkv1alpha1.Resource("invocation"))}
}

// Invocations returns an object that can list and get Invocations.
func (s *invocationLister) Invocations(namespace string) InvocationNamespaceLister {
	return invocationNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.Invocation](s.ResourceIndexer, namespace)}
}

// InvocationNamespaceLister helps list and get Invocations.
// All objects returned here must be treated as read-only.
type InvocationNamespaceLister interface {
	// List lists all Invocations in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.Invocation, err error)
	// Get retrieves the Invocation from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.Invocation, error)
	InvocationNamespaceListerExpansion
}

// invocationNamespaceLister implements the InvocationNamespaceLister
// interface.
type invocationNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.Invocation]
}
