/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// LoggingPolicyLister helps list LoggingPolicies.
// All objects returned here must be treated as read-only.
type LoggingPolicyLister interface {
	// List lists all LoggingPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.LoggingPolicy, err error)
	// LoggingPolicies returns an object that can list and get LoggingPolicies.
	LoggingPolicies(namespace string) LoggingPolicyNamespaceLister
	LoggingPolicyListerExpansion
}

// loggingPolicyLister implements the LoggingPolicyLister interface.
type loggingPolicyLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.LoggingPolicy]
}

// NewLoggingPolicyLister returns a new LoggingPolicyLister.
func NewLoggingPolicyLister(indexer cache.Indexer) LoggingPolicyLister {
	return &loggingPolicyLister{listers.New[*clrkv1alpha1.LoggingPolicy](indexer, clrkv1alpha1.Resource("loggingpolicy"))}
}

// LoggingPolicies returns an object that can list and get LoggingPolicies.
func (s *loggingPolicyLister) LoggingPolicies(namespace string) LoggingPolicyNamespaceLister {
	return loggingPolicyNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.LoggingPolicy](s.ResourceIndexer, namespace)}
}

// LoggingPolicyNamespaceLister helps list and get LoggingPolicies.
// All objects returned here must be treated as read-only.
type LoggingPolicyNamespaceLister interface {
	// List lists all LoggingPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.LoggingPolicy, err error)
	// Get retrieves the LoggingPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.LoggingPolicy, error)
	LoggingPolicyNamespaceListerExpansion
}

// loggingPolicyNamespaceLister implements the LoggingPolicyNamespaceLister
// interface.
type loggingPolicyNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.LoggingPolicy]
}
