/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// LoggingPolicyLister helps list LoggingPolicies.
// All objects returned here must be treated as read-only.
type LoggingPolicyLister interface {
	// List lists all LoggingPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.LoggingPolicy, err error)
	// LoggingPolicies returns an object that can list and get LoggingPolicies.
	LoggingPolicies(namespace string) LoggingPolicyNamespaceLister
	LoggingPolicyListerExpansion
}

// loggingPolicyLister implements the LoggingPolicyLister interface.
type loggingPolicyLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.LoggingPolicy]
}

// NewLoggingPolicyLister returns a new LoggingPolicyLister.
func NewLoggingPolicyLister(indexer cache.Indexer) LoggingPolicyLister {
	return &loggingPolicyLister{listers.New[*clrkv1alpha1.LoggingPolicy](indexer, clrkv1alpha1.Resource("loggingpolicy"))}
}

// LoggingPolicies returns an object that can list and get LoggingPolicies.
func (s *loggingPolicyLister) LoggingPolicies(namespace string) LoggingPolicyNamespaceLister {
	return loggingPolicyNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.LoggingPolicy](s.ResourceIndexer, namespace)}
}

// LoggingPolicyNamespaceLister helps list and get LoggingPolicies.
// All objects returned here must be treated as read-only.
type LoggingPolicyNamespaceLister interface {
	// List lists all LoggingPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.LoggingPolicy, err error)
	// Get retrieves the LoggingPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.LoggingPolicy, error)
	LoggingPolicyNamespaceListerExpansion
}

// loggingPolicyNamespaceLister implements the LoggingPolicyNamespaceLister
// interface.
type loggingPolicyNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.LoggingPolicy]
}
