/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MCPRouteLister helps list MCPRoutes.
// All objects returned here must be treated as read-only.
type MCPRouteLister interface {
	// List lists all MCPRoutes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.MCPRoute, err error)
	// MCPRoutes returns an object that can list and get MCPRoutes.
	MCPRoutes(namespace string) MCPRouteNamespaceLister
	MCPRouteListerExpansion
}

// mCPRouteLister implements the MCPRouteLister interface.
type mCPRouteLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.MCPRoute]
}

// NewMCPRouteLister returns a new MCPRouteLister.
func NewMCPRouteLister(indexer cache.Indexer) MCPRouteLister {
	return &mCPRouteLister{listers.New[*clrkv1alpha1.MCPRoute](indexer, clrkv1alpha1.Resource("mcproute"))}
}

// MCPRoutes returns an object that can list and get MCPRoutes.
func (s *mCPRouteLister) MCPRoutes(namespace string) MCPRouteNamespaceLister {
	return mCPRouteNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.MCPRoute](s.ResourceIndexer, namespace)}
}

// MCPRouteNamespaceLister helps list and get MCPRoutes.
// All objects returned here must be treated as read-only.
type MCPRouteNamespaceLister interface {
	// List lists all MCPRoutes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.MCPRoute, err error)
	// Get retrieves the MCPRoute from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.MCPRoute, error)
	MCPRouteNamespaceListerExpansion
}

// mCPRouteNamespaceLister implements the MCPRouteNamespaceLister
// interface.
type mCPRouteNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.MCPRoute]
}
