/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MCPRouteLister helps list MCPRoutes.
// All objects returned here must be treated as read-only.
type MCPRouteLister interface {
	// List lists all MCPRoutes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.MCPRoute, err error)
	// MCPRoutes returns an object that can list and get MCPRoutes.
	MCPRoutes(namespace string) MCPRouteNamespaceLister
	MCPRouteListerExpansion
}

// mCPRouteLister implements the MCPRouteLister interface.
type mCPRouteLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.MCPRoute]
}

// NewMCPRouteLister returns a new MCPRouteLister.
func NewMCPRouteLister(indexer cache.Indexer) MCPRouteLister {
	return &mCPRouteLister{listers.New[*clrkv1alpha1.MCPRoute](indexer, clrkv1alpha1.Resource("mcproute"))}
}

// MCPRoutes returns an object that can list and get MCPRoutes.
func (s *mCPRouteLister) MCPRoutes(namespace string) MCPRouteNamespaceLister {
	return mCPRouteNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.MCPRoute](s.ResourceIndexer, namespace)}
}

// MCPRouteNamespaceLister helps list and get MCPRoutes.
// All objects returned here must be treated as read-only.
type MCPRouteNamespaceLister interface {
	// List lists all MCPRoutes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.MCPRoute, err error)
	// Get retrieves the MCPRoute from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.MCPRoute, error)
	MCPRouteNamespaceListerExpansion
}

// mCPRouteNamespaceLister implements the MCPRouteNamespaceLister
// interface.
type mCPRouteNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.MCPRoute]
}
