/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RateLimitPolicyLister helps list RateLimitPolicies.
// All objects returned here must be treated as read-only.
type RateLimitPolicyLister interface {
	// List lists all RateLimitPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.RateLimitPolicy, err error)
	// RateLimitPolicies returns an object that can list and get RateLimitPolicies.
	RateLimitPolicies(namespace string) RateLimitPolicyNamespaceLister
	RateLimitPolicyListerExpansion
}

// rateLimitPolicyLister implements the RateLimitPolicyLister interface.
type rateLimitPolicyLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.RateLimitPolicy]
}

// NewRateLimitPolicyLister returns a new RateLimitPolicyLister.
func NewRateLimitPolicyLister(indexer cache.Indexer) RateLimitPolicyLister {
	return &rateLimitPolicyLister{listers.New[*clrkv1alpha1.RateLimitPolicy](indexer, clrkv1alpha1.Resource("ratelimitpolicy"))}
}

// RateLimitPolicies returns an object that can list and get RateLimitPolicies.
func (s *rateLimitPolicyLister) RateLimitPolicies(namespace string) RateLimitPolicyNamespaceLister {
	return rateLimitPolicyNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.RateLimitPolicy](s.ResourceIndexer, namespace)}
}

// RateLimitPolicyNamespaceLister helps list and get RateLimitPolicies.
// All objects returned here must be treated as read-only.
type RateLimitPolicyNamespaceLister interface {
	// List lists all RateLimitPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.RateLimitPolicy, err error)
	// Get retrieves the RateLimitPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.RateLimitPolicy, error)
	RateLimitPolicyNamespaceListerExpansion
}

// rateLimitPolicyNamespaceLister implements the RateLimitPolicyNamespaceLister
// interface.
type rateLimitPolicyNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.RateLimitPolicy]
}
