/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// TaskAgentLister helps list TaskAgents.
// All objects returned here must be treated as read-only.
type TaskAgentLister interface {
	// List lists all TaskAgents in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.TaskAgent, err error)
	// TaskAgents returns an object that can list and get TaskAgents.
	TaskAgents(namespace string) TaskAgentNamespaceLister
	TaskAgentListerExpansion
}

// taskAgentLister implements the TaskAgentLister interface.
type taskAgentLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.TaskAgent]
}

// NewTaskAgentLister returns a new TaskAgentLister.
func NewTaskAgentLister(indexer cache.Indexer) TaskAgentLister {
	return &taskAgentLister{listers.New[*clrkv1alpha1.TaskAgent](indexer, clrkv1alpha1.Resource("taskagent"))}
}

// TaskAgents returns an object that can list and get TaskAgents.
func (s *taskAgentLister) TaskAgents(namespace string) TaskAgentNamespaceLister {
	return taskAgentNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.TaskAgent](s.ResourceIndexer, namespace)}
}

// TaskAgentNamespaceLister helps list and get TaskAgents.
// All objects returned here must be treated as read-only.
type TaskAgentNamespaceLister interface {
	// List lists all TaskAgents in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.TaskAgent, err error)
	// Get retrieves the TaskAgent from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.TaskAgent, error)
	TaskAgentNamespaceListerExpansion
}

// taskAgentNamespaceLister implements the TaskAgentNamespaceLister
// interface.
type taskAgentNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.TaskAgent]
}
