/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// TaskAgentLister helps list TaskAgents.
// All objects returned here must be treated as read-only.
type TaskAgentLister interface {
	// List lists all TaskAgents in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.TaskAgent, err error)
	// TaskAgents returns an object that can list and get TaskAgents.
	TaskAgents(namespace string) TaskAgentNamespaceLister
	TaskAgentListerExpansion
}

// taskAgentLister implements the TaskAgentLister interface.
type taskAgentLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.TaskAgent]
}

// NewTaskAgentLister returns a new TaskAgentLister.
func NewTaskAgentLister(indexer cache.Indexer) TaskAgentLister {
	return &taskAgentLister{listers.New[*clrkv1alpha1.TaskAgent](indexer, clrkv1alpha1.Resource("taskagent"))}
}

// TaskAgents returns an object that can list and get TaskAgents.
func (s *taskAgentLister) TaskAgents(namespace string) TaskAgentNamespaceLister {
	return taskAgentNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.TaskAgent](s.ResourceIndexer, namespace)}
}

// TaskAgentNamespaceLister helps list and get TaskAgents.
// All objects returned here must be treated as read-only.
type TaskAgentNamespaceLister interface {
	// List lists all TaskAgents in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.TaskAgent, err error)
	// Get retrieves the TaskAgent from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.TaskAgent, error)
	TaskAgentNamespaceListerExpansion
}

// taskAgentNamespaceLister implements the TaskAgentNamespaceLister
// interface.
type taskAgentNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.TaskAgent]
}
