/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// WorkerPoolLister helps list WorkerPools.
// All objects returned here must be treated as read-only.
type WorkerPoolLister interface {
	// List lists all WorkerPools in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.WorkerPool, err error)
	// WorkerPools returns an object that can list and get WorkerPools.
	WorkerPools(namespace string) WorkerPoolNamespaceLister
	WorkerPoolListerExpansion
}

// workerPoolLister implements the WorkerPoolLister interface.
type workerPoolLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.WorkerPool]
}

// NewWorkerPoolLister returns a new WorkerPoolLister.
func NewWorkerPoolLister(indexer cache.Indexer) WorkerPoolLister {
	return &workerPoolLister{listers.New[*clrkv1alpha1.WorkerPool](indexer, clrkv1alpha1.Resource("workerpool"))}
}

// WorkerPools returns an object that can list and get WorkerPools.
func (s *workerPoolLister) WorkerPools(namespace string) WorkerPoolNamespaceLister {
	return workerPoolNamespaceLister{listers.NewNamespaced[*clrkv1alpha1.WorkerPool](s.ResourceIndexer, namespace)}
}

// WorkerPoolNamespaceLister helps list and get WorkerPools.
// All objects returned here must be treated as read-only.
type WorkerPoolNamespaceLister interface {
	// List lists all WorkerPools in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clrkv1alpha1.WorkerPool, err error)
	// Get retrieves the WorkerPool from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clrkv1alpha1.WorkerPool, error)
	WorkerPoolNamespaceListerExpansion
}

// workerPoolNamespaceLister implements the WorkerPoolNamespaceLister
// interface.
type workerPoolNamespaceLister struct {
	listers.ResourceIndexer[*clrkv1alpha1.WorkerPool]
}
