apiVersion: clrk.apoxy.dev/v1alpha1
kind: EgressGateway
metadata:
  name: echo-bot
spec:
  defaultPolicy: allow-all
  listeners:
    - name: egress
      protocol: TLS
      tls:
        mode: Terminate
  otlp:
    endpoint: http://otel-collector.observability.svc:4318
    captureBody:
      maxBytes: 65536
