//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package llmcall

import (
	json "encoding/json"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AudioPart) DeepCopyInto(out *AudioPart) {
	*out = *in
	in.Wire.DeepCopyInto(&out.Wire)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AudioPart.
func (in *AudioPart) DeepCopy() *AudioPart {
	if in == nil {
		return nil
	}
	out := new(AudioPart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Capabilities) DeepCopyInto(out *Capabilities) {
	*out = *in
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Capabilities.
func (in *Capabilities) DeepCopy() *Capabilities {
	if in == nil {
		return nil
	}
	out := new(Capabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Choice) DeepCopyInto(out *Choice) {
	*out = *in
	in.Message.DeepCopyInto(&out.Message)
	in.Wire.DeepCopyInto(&out.Wire)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Choice.
func (in *Choice) DeepCopy() *Choice {
	if in == nil {
		return nil
	}
	out := new(Choice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CitationPart) DeepCopyInto(out *CitationPart) {
	*out = *in
	in.Wire.DeepCopyInto(&out.Wire)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CitationPart.
func (in *CitationPart) DeepCopy() *CitationPart {
	if in == nil {
		return nil
	}
	out := new(CitationPart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtraField) DeepCopyInto(out *ExtraField) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtraField.
func (in *ExtraField) DeepCopy() *ExtraField {
	if in == nil {
		return nil
	}
	out := new(ExtraField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilePart) DeepCopyInto(out *FilePart) {
	*out = *in
	in.Wire.DeepCopyInto(&out.Wire)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilePart.
func (in *FilePart) DeepCopy() *FilePart {
	if in == nil {
		return nil
	}
	out := new(FilePart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenerationConfig) DeepCopyInto(out *GenerationConfig) {
	*out = *in
	if in.StopSequences != nil {
		in, out := &in.StopSequences, &out.StopSequences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Wire.DeepCopyInto(&out.Wire)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenerationConfig.
func (in *GenerationConfig) DeepCopy() *GenerationConfig {
	if in == nil {
		return nil
	}
	out := new(GenerationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePart) DeepCopyInto(out *ImagePart) {
	*out = *in
	in.Wire.DeepCopyInto(&out.Wire)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePart.
func (in *ImagePart) DeepCopy() *ImagePart {
	if in == nil {
		return nil
	}
	out := new(ImagePart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Message) DeepCopyInto(out *Message) {
	*out = *in
	if in.Parts != nil {
		in, out := &in.Parts, &out.Parts
		*out = make([]Part, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Wire.DeepCopyInto(&out.Wire)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Message.
func (in *Message) DeepCopy() *Message {
	if in == nil {
		return nil
	}
	out := new(Message)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Part) DeepCopyInto(out *Part) {
	*out = *in
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(TextPart)
		(*in).DeepCopyInto(*out)
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImagePart)
		(*in).DeepCopyInto(*out)
	}
	if in.Audio != nil {
		in, out := &in.Audio, &out.Audio
		*out = new(AudioPart)
		(*in).DeepCopyInto(*out)
	}
	if in.File != nil {
		in, out := &in.File, &out.File
		*out = new(FilePart)
		(*in).DeepCopyInto(*out)
	}
	if in.ToolCall != nil {
		in, out := &in.ToolCall, &out.ToolCall
		*out = new(ToolCallPart)
		(*in).DeepCopyInto(*out)
	}
	if in.ToolCallResponse != nil {
		in, out := &in.ToolCallResponse, &out.ToolCallResponse
		*out = new(ToolCallResponsePart)
		(*in).DeepCopyInto(*out)
	}
	if in.Reasoning != nil {
		in, out := &in.Reasoning, &out.Reasoning
		*out = new(ReasoningPart)
		(*in).DeepCopyInto(*out)
	}
	if in.Refusal != nil {
		in, out := &in.Refusal, &out.Refusal
		*out = new(RefusalPart)
		(*in).DeepCopyInto(*out)
	}
	if in.Citation != nil {
		in, out := &in.Citation, &out.Citation
		*out = new(CitationPart)
		(*in).DeepCopyInto(*out)
	}
	in.Wire.DeepCopyInto(&out.Wire)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Part.
func (in *Part) DeepCopy() *Part {
	if in == nil {
		return nil
	}
	out := new(Part)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReasoningPart) DeepCopyInto(out *ReasoningPart) {
	*out = *in
	in.Wire.DeepCopyInto(&out.Wire)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReasoningPart.
func (in *ReasoningPart) DeepCopy() *ReasoningPart {
	if in == nil {
		return nil
	}
	out := new(ReasoningPart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RefusalPart) DeepCopyInto(out *RefusalPart) {
	*out = *in
	in.Wire.DeepCopyInto(&out.Wire)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RefusalPart.
func (in *RefusalPart) DeepCopy() *RefusalPart {
	if in == nil {
		return nil
	}
	out := new(RefusalPart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Request) DeepCopyInto(out *Request) {
	*out = *in
	if in.System != nil {
		in, out := &in.System, &out.System
		*out = make([]Part, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]Message, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]ToolDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ToolChoice != nil {
		in, out := &in.ToolChoice, &out.ToolChoice
		*out = new(ToolChoice)
		(*in).DeepCopyInto(*out)
	}
	in.Generation.DeepCopyInto(&out.Generation)
	in.Wire.DeepCopyInto(&out.Wire)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Request.
func (in *Request) DeepCopy() *Request {
	if in == nil {
		return nil
	}
	out := new(Request)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Response) DeepCopyInto(out *Response) {
	*out = *in
	if in.Choices != nil {
		in, out := &in.Choices, &out.Choices
		*out = make([]Choice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Usage.DeepCopyInto(&out.Usage)
	in.Wire.DeepCopyInto(&out.Wire)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Response.
func (in *Response) DeepCopy() *Response {
	if in == nil {
		return nil
	}
	out := new(Response)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamContentEnd) DeepCopyInto(out *StreamContentEnd) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamContentEnd.
func (in *StreamContentEnd) DeepCopy() *StreamContentEnd {
	if in == nil {
		return nil
	}
	out := new(StreamContentEnd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamContentStart) DeepCopyInto(out *StreamContentStart) {
	*out = *in
	in.Part.DeepCopyInto(&out.Part)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamContentStart.
func (in *StreamContentStart) DeepCopy() *StreamContentStart {
	if in == nil {
		return nil
	}
	out := new(StreamContentStart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamError) DeepCopyInto(out *StreamError) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamError.
func (in *StreamError) DeepCopy() *StreamError {
	if in == nil {
		return nil
	}
	out := new(StreamError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamEvent) DeepCopyInto(out *StreamEvent) {
	*out = *in
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(StreamStart)
		**out = **in
	}
	if in.ContentStart != nil {
		in, out := &in.ContentStart, &out.ContentStart
		*out = new(StreamContentStart)
		(*in).DeepCopyInto(*out)
	}
	if in.TextDelta != nil {
		in, out := &in.TextDelta, &out.TextDelta
		*out = new(StreamTextDelta)
		**out = **in
	}
	if in.ToolCallDelta != nil {
		in, out := &in.ToolCallDelta, &out.ToolCallDelta
		*out = new(StreamToolCallDelta)
		**out = **in
	}
	if in.ReasoningDelta != nil {
		in, out := &in.ReasoningDelta, &out.ReasoningDelta
		*out = new(StreamReasoningDelta)
		**out = **in
	}
	if in.ContentEnd != nil {
		in, out := &in.ContentEnd, &out.ContentEnd
		*out = new(StreamContentEnd)
		**out = **in
	}
	if in.Usage != nil {
		in, out := &in.Usage, &out.Usage
		*out = new(Usage)
		(*in).DeepCopyInto(*out)
	}
	if in.Finish != nil {
		in, out := &in.Finish, &out.Finish
		*out = new(StreamFinish)
		**out = **in
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(StreamError)
		**out = **in
	}
	in.Wire.DeepCopyInto(&out.Wire)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamEvent.
func (in *StreamEvent) DeepCopy() *StreamEvent {
	if in == nil {
		return nil
	}
	out := new(StreamEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamFinish) DeepCopyInto(out *StreamFinish) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamFinish.
func (in *StreamFinish) DeepCopy() *StreamFinish {
	if in == nil {
		return nil
	}
	out := new(StreamFinish)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamReasoningDelta) DeepCopyInto(out *StreamReasoningDelta) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamReasoningDelta.
func (in *StreamReasoningDelta) DeepCopy() *StreamReasoningDelta {
	if in == nil {
		return nil
	}
	out := new(StreamReasoningDelta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamStart) DeepCopyInto(out *StreamStart) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamStart.
func (in *StreamStart) DeepCopy() *StreamStart {
	if in == nil {
		return nil
	}
	out := new(StreamStart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamTextDelta) DeepCopyInto(out *StreamTextDelta) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamTextDelta.
func (in *StreamTextDelta) DeepCopy() *StreamTextDelta {
	if in == nil {
		return nil
	}
	out := new(StreamTextDelta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamToolCallDelta) DeepCopyInto(out *StreamToolCallDelta) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamToolCallDelta.
func (in *StreamToolCallDelta) DeepCopy() *StreamToolCallDelta {
	if in == nil {
		return nil
	}
	out := new(StreamToolCallDelta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TextPart) DeepCopyInto(out *TextPart) {
	*out = *in
	in.Wire.DeepCopyInto(&out.Wire)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TextPart.
func (in *TextPart) DeepCopy() *TextPart {
	if in == nil {
		return nil
	}
	out := new(TextPart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolCallPart) DeepCopyInto(out *ToolCallPart) {
	*out = *in
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	in.Wire.DeepCopyInto(&out.Wire)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolCallPart.
func (in *ToolCallPart) DeepCopy() *ToolCallPart {
	if in == nil {
		return nil
	}
	out := new(ToolCallPart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolCallResponsePart) DeepCopyInto(out *ToolCallResponsePart) {
	*out = *in
	if in.Parts != nil {
		in, out := &in.Parts, &out.Parts
		*out = make([]Part, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Wire.DeepCopyInto(&out.Wire)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolCallResponsePart.
func (in *ToolCallResponsePart) DeepCopy() *ToolCallResponsePart {
	if in == nil {
		return nil
	}
	out := new(ToolCallResponsePart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolChoice) DeepCopyInto(out *ToolChoice) {
	*out = *in
	in.Wire.DeepCopyInto(&out.Wire)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolChoice.
func (in *ToolChoice) DeepCopy() *ToolChoice {
	if in == nil {
		return nil
	}
	out := new(ToolChoice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolDefinition) DeepCopyInto(out *ToolDefinition) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	in.Wire.DeepCopyInto(&out.Wire)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolDefinition.
func (in *ToolDefinition) DeepCopy() *ToolDefinition {
	if in == nil {
		return nil
	}
	out := new(ToolDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Usage) DeepCopyInto(out *Usage) {
	*out = *in
	in.Wire.DeepCopyInto(&out.Wire)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Usage.
func (in *Usage) DeepCopy() *Usage {
	if in == nil {
		return nil
	}
	out := new(Usage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wire) DeepCopyInto(out *Wire) {
	*out = *in
	if in.KeyOrder != nil {
		in, out := &in.KeyOrder, &out.KeyOrder
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Extras != nil {
		in, out := &in.Extras, &out.Extras
		*out = make([]ExtraField, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Shadow != nil {
		in, out := &in.Shadow, &out.Shadow
		*out = make(map[string]Shadow, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Hints != nil {
		in, out := &in.Hints, &out.Hints
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Raw != nil {
		in, out := &in.Raw, &out.Raw
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wire.
func (in *Wire) DeepCopy() *Wire {
	if in == nil {
		return nil
	}
	out := new(Wire)
	in.DeepCopyInto(out)
	return out
}
