/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	clrkv1alpha1 "github.com/apoxy-dev/clrk/client/versioned/typed/clrk/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeBackends implements BackendInterface
type fakeBackends struct {
	*gentype.FakeClientWithList[*v1alpha1.Backend, *v1alpha1.BackendList]
	Fake *FakeClrkV1alpha1
}

func newFakeBackends(fake *FakeClrkV1alpha1, namespace string) clrkv1alpha1.BackendInterface {
	return &fakeBackends{
		gentype.NewFakeClientWithList[*v1alpha1.Backend, *v1alpha1.BackendList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("backends"),
			v1alpha1.SchemeGroupVersion.WithKind("Backend"),
			func() *v1alpha1.Backend { return &v1alpha1.Backend{} },
			func() *v1alpha1.BackendList { return &v1alpha1.BackendList{} },
			func(dst, src *v1alpha1.BackendList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.BackendList) []*v1alpha1.Backend { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.BackendList, items []*v1alpha1.Backend) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
