/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	clrkv1alpha1 "github.com/apoxy-dev/clrk/client/versioned/typed/clrk/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeMCPRoutes implements MCPRouteInterface
type fakeMCPRoutes struct {
	*gentype.FakeClientWithList[*v1alpha1.MCPRoute, *v1alpha1.MCPRouteList]
	Fake *FakeClrkV1alpha1
}

func newFakeMCPRoutes(fake *FakeClrkV1alpha1, namespace string) clrkv1alpha1.MCPRouteInterface {
	return &fakeMCPRoutes{
		gentype.NewFakeClientWithList[*v1alpha1.MCPRoute, *v1alpha1.MCPRouteList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("mcproutes"),
			v1alpha1.SchemeGroupVersion.WithKind("MCPRoute"),
			func() *v1alpha1.MCPRoute { return &v1alpha1.MCPRoute{} },
			func() *v1alpha1.MCPRouteList { return &v1alpha1.MCPRouteList{} },
			func(dst, src *v1alpha1.MCPRouteList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.MCPRouteList) []*v1alpha1.MCPRoute { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.MCPRouteList, items []*v1alpha1.MCPRoute) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
