/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	clrkv1alpha1 "github.com/apoxy-dev/clrk/client/versioned/typed/clrk/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeAgentSandboxRevisions implements AgentSandboxRevisionInterface
type fakeAgentSandboxRevisions struct {
	*gentype.FakeClientWithList[*v1alpha1.AgentSandboxRevision, *v1alpha1.AgentSandboxRevisionList]
	Fake *FakeClrkV1alpha1
}

func newFakeAgentSandboxRevisions(fake *FakeClrkV1alpha1, namespace string) clrkv1alpha1.AgentSandboxRevisionInterface {
	return &fakeAgentSandboxRevisions{
		gentype.NewFakeClientWithList[*v1alpha1.AgentSandboxRevision, *v1alpha1.AgentSandboxRevisionList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("agentsandboxrevisions"),
			v1alpha1.SchemeGroupVersion.WithKind("AgentSandboxRevision"),
			func() *v1alpha1.AgentSandboxRevision { return &v1alpha1.AgentSandboxRevision{} },
			func() *v1alpha1.AgentSandboxRevisionList { return &v1alpha1.AgentSandboxRevisionList{} },
			func(dst, src *v1alpha1.AgentSandboxRevisionList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.AgentSandboxRevisionList) []*v1alpha1.AgentSandboxRevision {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.AgentSandboxRevisionList, items []*v1alpha1.AgentSandboxRevision) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
