/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	clrkv1alpha1 "github.com/apoxy-dev/clrk/client/versioned/typed/clrk/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeWorkerPools implements WorkerPoolInterface
type fakeWorkerPools struct {
	*gentype.FakeClientWithList[*v1alpha1.WorkerPool, *v1alpha1.WorkerPoolList]
	Fake *FakeClrkV1alpha1
}

func newFakeWorkerPools(fake *FakeClrkV1alpha1, namespace string) clrkv1alpha1.WorkerPoolInterface {
	return &fakeWorkerPools{
		gentype.NewFakeClientWithList[*v1alpha1.WorkerPool, *v1alpha1.WorkerPoolList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("workerpools"),
			v1alpha1.SchemeGroupVersion.WithKind("WorkerPool"),
			func() *v1alpha1.WorkerPool { return &v1alpha1.WorkerPool{} },
			func() *v1alpha1.WorkerPoolList { return &v1alpha1.WorkerPoolList{} },
			func(dst, src *v1alpha1.WorkerPoolList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.WorkerPoolList) []*v1alpha1.WorkerPool { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.WorkerPoolList, items []*v1alpha1.WorkerPool) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
