/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/apoxy-dev/clrk/client/versioned/typed/clrk/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeClrkV1alpha1 struct {
	*testing.Fake
}

func (c *FakeClrkV1alpha1) AIProviderRoutes(namespace string) v1alpha1.AIProviderRouteInterface {
	return newFakeAIProviderRoutes(c, namespace)
}

func (c *FakeClrkV1alpha1) AgentSandboxRevisions(namespace string) v1alpha1.AgentSandboxRevisionInterface {
	return newFakeAgentSandboxRevisions(c, namespace)
}

func (c *FakeClrkV1alpha1) Backends(namespace string) v1alpha1.BackendInterface {
	return newFakeBackends(c, namespace)
}

func (c *FakeClrkV1alpha1) CredentialInjectionPolicies(namespace string) v1alpha1.CredentialInjectionPolicyInterface {
	return newFakeCredentialInjectionPolicies(c, namespace)
}

func (c *FakeClrkV1alpha1) DaemonAgents(namespace string) v1alpha1.DaemonAgentInterface {
	return newFakeDaemonAgents(c, namespace)
}

func (c *FakeClrkV1alpha1) EgressDenyPolicies(namespace string) v1alpha1.EgressDenyPolicyInterface {
	return newFakeEgressDenyPolicies(c, namespace)
}

func (c *FakeClrkV1alpha1) EgressGateways(namespace string) v1alpha1.EgressGatewayInterface {
	return newFakeEgressGateways(c, namespace)
}

func (c *FakeClrkV1alpha1) EgressL4Routes(namespace string) v1alpha1.EgressL4RouteInterface {
	return newFakeEgressL4Routes(c, namespace)
}

func (c *FakeClrkV1alpha1) FallbackRoutingPolicies(namespace string) v1alpha1.FallbackRoutingPolicyInterface {
	return newFakeFallbackRoutingPolicies(c, namespace)
}

func (c *FakeClrkV1alpha1) Invocations(namespace string) v1alpha1.InvocationInterface {
	return newFakeInvocations(c, namespace)
}

func (c *FakeClrkV1alpha1) LoggingPolicies(namespace string) v1alpha1.LoggingPolicyInterface {
	return newFakeLoggingPolicies(c, namespace)
}

func (c *FakeClrkV1alpha1) MCPRoutes(namespace string) v1alpha1.MCPRouteInterface {
	return newFakeMCPRoutes(c, namespace)
}

func (c *FakeClrkV1alpha1) RateLimitPolicies(namespace string) v1alpha1.RateLimitPolicyInterface {
	return newFakeRateLimitPolicies(c, namespace)
}

func (c *FakeClrkV1alpha1) TaskAgents(namespace string) v1alpha1.TaskAgentInterface {
	return newFakeTaskAgents(c, namespace)
}

func (c *FakeClrkV1alpha1) WorkerPools(namespace string) v1alpha1.WorkerPoolInterface {
	return newFakeWorkerPools(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeClrkV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
