/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	clrkv1alpha1 "github.com/apoxy-dev/clrk/client/versioned/typed/clrk/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeCredentialInjectionPolicies implements CredentialInjectionPolicyInterface
type fakeCredentialInjectionPolicies struct {
	*gentype.FakeClientWithList[*v1alpha1.CredentialInjectionPolicy, *v1alpha1.CredentialInjectionPolicyList]
	Fake *FakeClrkV1alpha1
}

func newFakeCredentialInjectionPolicies(fake *FakeClrkV1alpha1, namespace string) clrkv1alpha1.CredentialInjectionPolicyInterface {
	return &fakeCredentialInjectionPolicies{
		gentype.NewFakeClientWithList[*v1alpha1.CredentialInjectionPolicy, *v1alpha1.CredentialInjectionPolicyList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("credentialinjectionpolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("CredentialInjectionPolicy"),
			func() *v1alpha1.CredentialInjectionPolicy { return &v1alpha1.CredentialInjectionPolicy{} },
			func() *v1alpha1.CredentialInjectionPolicyList { return &v1alpha1.CredentialInjectionPolicyList{} },
			func(dst, src *v1alpha1.CredentialInjectionPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.CredentialInjectionPolicyList) []*v1alpha1.CredentialInjectionPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.CredentialInjectionPolicyList, items []*v1alpha1.CredentialInjectionPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
