/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	clrkv1alpha1 "github.com/apoxy-dev/clrk/client/versioned/typed/clrk/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeEgressL4Routes implements EgressL4RouteInterface
type fakeEgressL4Routes struct {
	*gentype.FakeClientWithList[*v1alpha1.EgressL4Route, *v1alpha1.EgressL4RouteList]
	Fake *FakeClrkV1alpha1
}

func newFakeEgressL4Routes(fake *FakeClrkV1alpha1, namespace string) clrkv1alpha1.EgressL4RouteInterface {
	return &fakeEgressL4Routes{
		gentype.NewFakeClientWithList[*v1alpha1.EgressL4Route, *v1alpha1.EgressL4RouteList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("egressl4routes"),
			v1alpha1.SchemeGroupVersion.WithKind("EgressL4Route"),
			func() *v1alpha1.EgressL4Route { return &v1alpha1.EgressL4Route{} },
			func() *v1alpha1.EgressL4RouteList { return &v1alpha1.EgressL4RouteList{} },
			func(dst, src *v1alpha1.EgressL4RouteList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.EgressL4RouteList) []*v1alpha1.EgressL4Route {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.EgressL4RouteList, items []*v1alpha1.EgressL4Route) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
