/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/apoxy-dev/clrk/client/versioned/typed/clrk/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeClrkV1alpha1 struct {
	*testing.Fake
}

func (c *FakeClrkV1alpha1) AIProviderRoutes(namespace string) v1alpha1.AIProviderRouteInterface {
	return newFakeAIProviderRoutes(c, namespace)
}

func (c *FakeClrkV1alpha1) AgentSandboxRevisions(namespace string) v1alpha1.AgentSandboxRevisionInterface {
	return newFakeAgentSandboxRevisions(c, namespace)
}

func (c *FakeClrkV1alpha1) Backends(namespace string) v1alpha1.BackendInterface {
	return newFakeBackends(c, namespace)
}

func (c *FakeClrkV1alpha1) CredentialInjectionPolicies(namespace string) v1alpha1.CredentialInjectionPolicyInterface {
	return newFakeCredentialInjectionPolicies(c, namespace)
}

func (c *FakeClrkV1alpha1) DaemonAgents(namespace string) v1alpha1.DaemonAgentInterface {
	return newFakeDaemonAgents(c, namespace)
}

func (c *FakeClrkV1alpha1) EgressDenyPolicies(namespace string) v1alpha1.EgressDenyPolicyInterface {
	return newFakeEgressDenyPolicies(c, namespace)
}

func (c *FakeClrkV1alpha1) EgressGateways(namespace string) v1alpha1.EgressGatewayInterface {
	return newFakeEgressGateways(c, namespace)
}

func (c *FakeClrkV1alpha1) EgressL4Routes(namespace string) v1alpha1.EgressL4RouteInterface {
	return newFakeEgressL4Routes(c, namespace)
}

func (c *FakeClrkV1alpha1) Invocations(namespace string) v1alpha1.InvocationInterface {
	return newFakeInvocations(c, namespace)
}

func (c *FakeClrkV1alpha1) LoggingPolicies(namespace string) v1alpha1.LoggingPolicyInterface {
	return newFakeLoggingPolicies(c, namespace)
}

func (c *FakeClrkV1alpha1) MCPRoutes(namespace string) v1alpha1.MCPRouteInterface {
	return newFakeMCPRoutes(c, namespace)
}

func (c *FakeClrkV1alpha1) RateLimitPolicies(namespace string) v1alpha1.RateLimitPolicyInterface {
	return newFakeRateLimitPolicies(c, namespace)
}

func (c *FakeClrkV1alpha1) TaskAgents(namespace string) v1alpha1.TaskAgentInterface {
	return newFakeTaskAgents(c, namespace)
}

func (c *FakeClrkV1alpha1) WorkerPools(namespace string) v1alpha1.WorkerPoolInterface {
	return newFakeWorkerPools(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeClrkV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
