/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	clrkv1alpha1 "github.com/apoxy-dev/clrk/client/versioned/typed/clrk/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeLoggingPolicies implements LoggingPolicyInterface
type fakeLoggingPolicies struct {
	*gentype.FakeClientWithList[*v1alpha1.LoggingPolicy, *v1alpha1.LoggingPolicyList]
	Fake *FakeClrkV1alpha1
}

func newFakeLoggingPolicies(fake *FakeClrkV1alpha1, namespace string) clrkv1alpha1.LoggingPolicyInterface {
	return &fakeLoggingPolicies{
		gentype.NewFakeClientWithList[*v1alpha1.LoggingPolicy, *v1alpha1.LoggingPolicyList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("loggingpolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("LoggingPolicy"),
			func() *v1alpha1.LoggingPolicy { return &v1alpha1.LoggingPolicy{} },
			func() *v1alpha1.LoggingPolicyList { return &v1alpha1.LoggingPolicyList{} },
			func(dst, src *v1alpha1.LoggingPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.LoggingPolicyList) []*v1alpha1.LoggingPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.LoggingPolicyList, items []*v1alpha1.LoggingPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
