// WorkerStatusService is served by every clrk worker pod on a dedicated
// gRPC port. The controller-manager opens one Watch stream per pod from
// the WorkerPool's EndpointSlice and feeds the in-memory state map that
// the ingress ext_proc consults to pick a per-execution worker.
//
// First message on a stream is a snapshot (snapshot=true). Subsequent
// messages are deltas (snapshot=false) that the consumer applies on
// top of its last seen state. The server emits an empty heartbeat
// every 5s when no real state change has fired so the consumer can
// detect a dead stream via inactivity.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: clrk/v1alpha1/worker_status.proto

package workerstatusv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerStatusService_Watch_FullMethodName = "/clrk.v1alpha1.WorkerStatusService/Watch"
)

// WorkerStatusServiceClient is the client API for WorkerStatusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerStatusServiceClient interface {
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkerStatus], error)
}

type workerStatusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerStatusServiceClient(cc grpc.ClientConnInterface) WorkerStatusServiceClient {
	return &workerStatusServiceClient{cc}
}

func (c *workerStatusServiceClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkerStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerStatusService_ServiceDesc.Streams[0], WorkerStatusService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WorkerStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerStatusService_WatchClient = grpc.ServerStreamingClient[WorkerStatus]

// WorkerStatusServiceServer is the server API for WorkerStatusService service.
// All implementations must embed UnimplementedWorkerStatusServiceServer
// for forward compatibility.
type WorkerStatusServiceServer interface {
	Watch(*WatchRequest, grpc.ServerStreamingServer[WorkerStatus]) error
	mustEmbedUnimplementedWorkerStatusServiceServer()
}

// UnimplementedWorkerStatusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerStatusServiceServer struct{}

func (UnimplementedWorkerStatusServiceServer) Watch(*WatchRequest, grpc.ServerStreamingServer[WorkerStatus]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedWorkerStatusServiceServer) mustEmbedUnimplementedWorkerStatusServiceServer() {}
func (UnimplementedWorkerStatusServiceServer) testEmbeddedByValue()                             {}

// UnsafeWorkerStatusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerStatusServiceServer will
// result in compilation errors.
type UnsafeWorkerStatusServiceServer interface {
	mustEmbedUnimplementedWorkerStatusServiceServer()
}

func RegisterWorkerStatusServiceServer(s grpc.ServiceRegistrar, srv WorkerStatusServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerStatusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerStatusService_ServiceDesc, srv)
}

func _WorkerStatusService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerStatusServiceServer).Watch(m, &grpc.GenericServerStream[WatchRequest, WorkerStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerStatusService_WatchServer = grpc.ServerStreamingServer[WorkerStatus]

// WorkerStatusService_ServiceDesc is the grpc.ServiceDesc for WorkerStatusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerStatusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clrk.v1alpha1.WorkerStatusService",
	HandlerType: (*WorkerStatusServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _WorkerStatusService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "clrk/v1alpha1/worker_status.proto",
}
