// WorkerStatusService is served by every clrk worker pod on a dedicated
// gRPC port. The controller-manager opens one Watch stream per pod from
// the WorkerPool's EndpointSlice and feeds the in-memory state map that
// the ingress ext_proc consults to pick a per-execution worker.
//
// First message on a stream is a snapshot (snapshot=true). Subsequent
// messages are deltas (snapshot=false) that the consumer applies on
// top of its last seen state. The server emits an empty heartbeat
// every 5s when no real state change has fired so the consumer can
// detect a dead stream via inactivity.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: clrk/v1alpha1/worker_status.proto

package workerstatusv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_clrk_v1alpha1_worker_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clrk_v1alpha1_worker_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_clrk_v1alpha1_worker_status_proto_rawDescGZIP(), []int{0}
}

type WorkerStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Monotonic counter that increments on every server-side state
	// mutation. Heartbeat messages reuse the last emitted value.
	UpdateSeq uint64 `protobuf:"varint,1,opt,name=update_seq,json=updateSeq,proto3" json:"update_seq,omitempty"`
	// True for the snapshot sent immediately after a stream opens.
	// False for deltas + heartbeats.
	Snapshot bool `protobuf:"varint,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	// True when this message carries no state change; emitted every
	// 5s by default to keep the stream alive.
	Heartbeat bool `protobuf:"varint,3,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	// Warm sandboxes ready to accept a dispatch (Phase=Ready in the
	// worker's SandboxManager). One entry per (ns, agent, revision).
	WarmRevisions []*WarmRevision `protobuf:"bytes,4,rep,name=warm_revisions,json=warmRevisions,proto3" json:"warm_revisions,omitempty"`
	// In-flight dispatches per (ns, agent). agent identifies the
	// TaskAgent name. These directly drive the cluster-wide
	// MaxConcurrent enforcement in the ingress ext_proc.
	InFlight []*InFlight `protobuf:"bytes,5,rep,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	// Revisions whose images are pulled into the worker's image
	// store. Routing prefers a worker that already has the image
	// even if no warm sandbox exists.
	CachedImages []*CachedImage `protobuf:"bytes,6,rep,name=cached_images,json=cachedImages,proto3" json:"cached_images,omitempty"`
	// Best-effort resource utilization. Snapshot value, not a delta.
	Resources *ResourceUsage `protobuf:"bytes,7,opt,name=resources,proto3" json:"resources,omitempty"`
}

func (x *WorkerStatus) Reset() {
	*x = WorkerStatus{}
	mi := &file_clrk_v1alpha1_worker_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatus) ProtoMessage() {}

func (x *WorkerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_clrk_v1alpha1_worker_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatus.ProtoReflect.Descriptor instead.
func (*WorkerStatus) Descriptor() ([]byte, []int) {
	return file_clrk_v1alpha1_worker_status_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerStatus) GetUpdateSeq() uint64 {
	if x != nil {
		return x.UpdateSeq
	}
	return 0
}

func (x *WorkerStatus) GetSnapshot() bool {
	if x != nil {
		return x.Snapshot
	}
	return false
}

func (x *WorkerStatus) GetHeartbeat() bool {
	if x != nil {
		return x.Heartbeat
	}
	return false
}

func (x *WorkerStatus) GetWarmRevisions() []*WarmRevision {
	if x != nil {
		return x.WarmRevisions
	}
	return nil
}

func (x *WorkerStatus) GetInFlight() []*InFlight {
	if x != nil {
		return x.InFlight
	}
	return nil
}

func (x *WorkerStatus) GetCachedImages() []*CachedImage {
	if x != nil {
		return x.CachedImages
	}
	return nil
}

func (x *WorkerStatus) GetResources() *ResourceUsage {
	if x != nil {
		return x.Resources
	}
	return nil
}

type WarmRevision struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Agent     string `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Revision  string `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	// Number of warm sandboxes for this triple. >= 1.
	Count uint32 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *WarmRevision) Reset() {
	*x = WarmRevision{}
	mi := &file_clrk_v1alpha1_worker_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarmRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarmRevision) ProtoMessage() {}

func (x *WarmRevision) ProtoReflect() protoreflect.Message {
	mi := &file_clrk_v1alpha1_worker_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarmRevision.ProtoReflect.Descriptor instead.
func (*WarmRevision) Descriptor() ([]byte, []int) {
	return file_clrk_v1alpha1_worker_status_proto_rawDescGZIP(), []int{2}
}

func (x *WarmRevision) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WarmRevision) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *WarmRevision) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *WarmRevision) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type InFlight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Agent     string `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Count     uint32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *InFlight) Reset() {
	*x = InFlight{}
	mi := &file_clrk_v1alpha1_worker_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InFlight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InFlight) ProtoMessage() {}

func (x *InFlight) ProtoReflect() protoreflect.Message {
	mi := &file_clrk_v1alpha1_worker_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InFlight.ProtoReflect.Descriptor instead.
func (*InFlight) Descriptor() ([]byte, []int) {
	return file_clrk_v1alpha1_worker_status_proto_rawDescGZIP(), []int{3}
}

func (x *InFlight) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *InFlight) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *InFlight) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CachedImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Fully qualified image reference (e.g. "registry/foo:abc123").
	ImageRef string `protobuf:"bytes,1,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
}

func (x *CachedImage) Reset() {
	*x = CachedImage{}
	mi := &file_clrk_v1alpha1_worker_status_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CachedImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachedImage) ProtoMessage() {}

func (x *CachedImage) ProtoReflect() protoreflect.Message {
	mi := &file_clrk_v1alpha1_worker_status_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachedImage.ProtoReflect.Descriptor instead.
func (*CachedImage) Descriptor() ([]byte, []int) {
	return file_clrk_v1alpha1_worker_status_proto_rawDescGZIP(), []int{4}
}

func (x *CachedImage) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

type ResourceUsage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 0..1.0 reflecting recent CPU usage on this worker.
	CpuFraction float64 `protobuf:"fixed64,1,opt,name=cpu_fraction,json=cpuFraction,proto3" json:"cpu_fraction,omitempty"`
	// Resident memory in bytes used by sandboxes on this worker.
	MemoryBytes uint64 `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_clrk_v1alpha1_worker_status_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_clrk_v1alpha1_worker_status_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_clrk_v1alpha1_worker_status_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceUsage) GetCpuFraction() float64 {
	if x != nil {
		return x.CpuFraction
	}
	return 0
}

func (x *ResourceUsage) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

var File_clrk_v1alpha1_worker_status_proto protoreflect.FileDescriptor

var file_clrk_v1alpha1_worker_status_proto_rawDesc = []byte{
	0x0a, 0x21, 0x63, 0x6c, 0x72, 0x6b, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f,
	0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x6c, 0x72, 0x6b, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x22, 0x0e, 0x0a, 0x0c, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0xde, 0x02, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65,
	0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x42, 0x0a, 0x0e,
	0x77, 0x61, 0x72, 0x6d, 0x5f, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6c, 0x72, 0x6b, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x57, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x0d, 0x77, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x34, 0x0a, 0x09, 0x69, 0x6e, 0x5f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6c, 0x72, 0x6b, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2e, 0x49, 0x6e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x08, 0x69, 0x6e,
	0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x3f, 0x0a, 0x0d, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64,
	0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x63, 0x6c, 0x72, 0x6b, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x0c, 0x63, 0x61, 0x63, 0x68, 0x65,
	0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6c, 0x72,
	0x6b, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x22, 0x74, 0x0a, 0x0c, 0x57, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x54, 0x0a, 0x08, 0x49, 0x6e, 0x46,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x2a, 0x0a, 0x0b, 0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x22, 0x55, 0x0a, 0x0d, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x70, 0x75, 0x5f, 0x66, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0b, 0x63, 0x70, 0x75, 0x46, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x32, 0x5a, 0x0a, 0x13, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x05, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x12, 0x1b, 0x2e, 0x63, 0x6c, 0x72, 0x6b, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x63, 0x6c, 0x72, 0x6b, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x30, 0x01, 0x42, 0x44,
	0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x70, 0x6f,
	0x78, 0x79, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x63, 0x6c, 0x72, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x63, 0x6c, 0x72, 0x6b, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x3b,
	0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clrk_v1alpha1_worker_status_proto_rawDescOnce sync.Once
	file_clrk_v1alpha1_worker_status_proto_rawDescData = file_clrk_v1alpha1_worker_status_proto_rawDesc
)

func file_clrk_v1alpha1_worker_status_proto_rawDescGZIP() []byte {
	file_clrk_v1alpha1_worker_status_proto_rawDescOnce.Do(func() {
		file_clrk_v1alpha1_worker_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_clrk_v1alpha1_worker_status_proto_rawDescData)
	})
	return file_clrk_v1alpha1_worker_status_proto_rawDescData
}

var file_clrk_v1alpha1_worker_status_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_clrk_v1alpha1_worker_status_proto_goTypes = []any{
	(*WatchRequest)(nil),  // 0: clrk.v1alpha1.WatchRequest
	(*WorkerStatus)(nil),  // 1: clrk.v1alpha1.WorkerStatus
	(*WarmRevision)(nil),  // 2: clrk.v1alpha1.WarmRevision
	(*InFlight)(nil),      // 3: clrk.v1alpha1.InFlight
	(*CachedImage)(nil),   // 4: clrk.v1alpha1.CachedImage
	(*ResourceUsage)(nil), // 5: clrk.v1alpha1.ResourceUsage
}
var file_clrk_v1alpha1_worker_status_proto_depIdxs = []int32{
	2, // 0: clrk.v1alpha1.WorkerStatus.warm_revisions:type_name -> clrk.v1alpha1.WarmRevision
	3, // 1: clrk.v1alpha1.WorkerStatus.in_flight:type_name -> clrk.v1alpha1.InFlight
	4, // 2: clrk.v1alpha1.WorkerStatus.cached_images:type_name -> clrk.v1alpha1.CachedImage
	5, // 3: clrk.v1alpha1.WorkerStatus.resources:type_name -> clrk.v1alpha1.ResourceUsage
	0, // 4: clrk.v1alpha1.WorkerStatusService.Watch:input_type -> clrk.v1alpha1.WatchRequest
	1, // 5: clrk.v1alpha1.WorkerStatusService.Watch:output_type -> clrk.v1alpha1.WorkerStatus
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_clrk_v1alpha1_worker_status_proto_init() }
func file_clrk_v1alpha1_worker_status_proto_init() {
	if File_clrk_v1alpha1_worker_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clrk_v1alpha1_worker_status_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clrk_v1alpha1_worker_status_proto_goTypes,
		DependencyIndexes: file_clrk_v1alpha1_worker_status_proto_depIdxs,
		MessageInfos:      file_clrk_v1alpha1_worker_status_proto_msgTypes,
	}.Build()
	File_clrk_v1alpha1_worker_status_proto = out.File
	file_clrk_v1alpha1_worker_status_proto_rawDesc = nil
	file_clrk_v1alpha1_worker_status_proto_goTypes = nil
	file_clrk_v1alpha1_worker_status_proto_depIdxs = nil
}
