/**
 * schema.d.ts + per-kind tray schema codegen (openapi-typescript).
 *
 * Generates `apps/clrk-console/src/schema/schema.d.ts` and
 * `apps/clrk-console/src/schema/resource-schemas.ts` from the clrk apiserver
 * OpenAPI. These are clrk-specific (the single `clrk.apoxy.dev/v1alpha1` group),
 * so they live in the clrk app rather than the app-agnostic `@apoxy/console-core`.
 * The committed output is the source of truth; it is not fetched at runtime.
 *
 * Source resolution (offline preferred — hermetic CI, no running apiserver):
 *   1. `console/openapi.json`, rendered offline from `api/generated/zz_generated.openapi.go`
 *      by the `cmd/openapi-dump` Go command. Regenerate the spec with:
 *        go run ./cmd/openapi-dump -o console/openapi.json -title "CLRK Console API" -version v0
 *      (run from the clrk repo root). Both the spec and this file's output are
 *      committed; CI regenerates and diffs them to catch drift.
 *   2. Fallback: a live apiserver's OpenAPI at $CLRK_OPENAPI_URL.
 */
import { access, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'
import { emitResourceSchemasModule, type OpenAPIDoc } from './openapi-to-schemas'

const here = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(here, '../apps/clrk-console/src/schema/schema.d.ts')
const SCHEMAS_OUT = resolve(here, '../apps/clrk-console/src/schema/resource-schemas.ts')
const LOCAL_SPEC = resolve(here, '../openapi.json')
const REMOTE = process.env.CLRK_OPENAPI_URL

async function resolveSource(): Promise<URL> {
  try {
    await access(LOCAL_SPEC)
    return new URL(`file://${LOCAL_SPEC}`)
  } catch {
    // no local spec
  }
  if (REMOTE) return new URL(REMOTE)
  throw new Error(
    'No OpenAPI source. Render console/openapi.json offline from ' +
      'api/generated/zz_generated.openapi.go (preferred), or set CLRK_OPENAPI_URL.',
  )
}

const source = await resolveSource()
const ast = await openapiTS(source)
const banner =
  '// GENERATED by console/scripts/generate-schema.ts (openapi-typescript) — do not edit by hand.\n'
await writeFile(OUT, banner + astToString(ast))
console.log(`Wrote ${OUT} from ${source.href}`)

// Per-kind tray validation schemas, extracted from the same OpenAPI document.
// (Read the JSON directly — openapi-typescript hands back only the TS AST.)
const raw = source.protocol === 'file:' ? await readFile(source, 'utf8') : await (await fetch(source)).text()
await writeFile(SCHEMAS_OUT, emitResourceSchemasModule(JSON.parse(raw) as OpenAPIDoc))
console.log(`Wrote ${SCHEMAS_OUT}`)
