/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by informer-gen. DO NOT EDIT.

package informers

import (
	fmt "fmt"

	v1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=clrk.apoxy.dev, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithResource("aiproviderroutes"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Clrk().V1alpha1().AIProviderRoutes().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("agentsandboxrevisions"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Clrk().V1alpha1().AgentSandboxRevisions().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("credentialinjectionpolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Clrk().V1alpha1().CredentialInjectionPolicies().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("daemonagents"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Clrk().V1alpha1().DaemonAgents().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("egressdenypolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Clrk().V1alpha1().EgressDenyPolicies().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("egressgateways"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Clrk().V1alpha1().EgressGateways().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("egressl4routes"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Clrk().V1alpha1().EgressL4Routes().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("loggingpolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Clrk().V1alpha1().LoggingPolicies().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("mcproutes"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Clrk().V1alpha1().MCPRoutes().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("ratelimitpolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Clrk().V1alpha1().RateLimitPolicies().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("taskagents"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Clrk().V1alpha1().TaskAgents().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("workerpools"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Clrk().V1alpha1().WorkerPools().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
