// Package egextension implements the Envoy Gateway extension server that
// rewrites xDS resources on the way out of EG's translator. We use it for
// two things:
//
//  1. Inject the grpc_certificate_provider custom handshaker onto every
//     egress listener's DownstreamTlsContext, with initial gRPC metadata
//     scoping the cert-provider lookup to the right EgressGateway.
//  2. Append an ext_proc HTTP filter to every HCM filter chain so body
//     capture lands on the clrk controller-manager's ext_proc service.
//
// Only listeners generated by clrk-owned Gateways should pass through
// here: clrk's EgressGateway controller creates Gateways with names of
// the form "clrk-eg-<egName>" under a dedicated GatewayClass, and the
// EnvoyProxy attached to that GatewayClass points at this extension. If
// the extension sees a listener that does not match that naming
// convention it leaves it untouched.
package egextension

import (
	"context"
	"fmt"
	"strings"
	"time"

	corev3 "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
	listenerv3 "github.com/envoyproxy/go-control-plane/envoy/config/listener/v3"
	extprocv3 "github.com/envoyproxy/go-control-plane/envoy/extensions/filters/http/ext_proc/v3"
	hcmv3 "github.com/envoyproxy/go-control-plane/envoy/extensions/filters/network/http_connection_manager/v3"
	pb "github.com/envoyproxy/gateway/proto/extension"
	"google.golang.org/protobuf/types/known/anypb"
	"google.golang.org/protobuf/types/known/durationpb"
	ctrllog "sigs.k8s.io/controller-runtime/pkg/log"

	tlsv3 "github.com/apoxy-dev/envoy-go/envoy/extensions/transport_sockets/tls/v3"

	"github.com/apoxy-dev/clrk/internal/certprovider"
)

// Well-known extension names.
const (
	grpcCertProviderHandshakerName = "envoy.tls_handshakers.grpc_certificate_provider"
	extProcFilterName              = "envoy.filters.http.ext_proc"
	routerFilterName               = "envoy.filters.http.router"
	tlsTransportSocketName         = "envoy.transport_sockets.tls"
)

// GatewayNamePrefix is the prefix the EgressGateway controller uses when
// creating Gateway resources. We parse it off listener names so every
// other Gateway (ingress etc.) is left alone.
const GatewayNamePrefix = "clrk-eg-"

const (
	defaultHandshakerTimeout  = 60 * time.Second
	defaultHandshakerCacheTTL = 1 * time.Hour
	defaultHandshakerCacheMax = 1000

	defaultExtProcTimeout = 30 * time.Second
)

// Server implements envoyproxy/gateway extension.EnvoyGatewayExtensionServer.
// Register with a gRPC server via pb.RegisterEnvoyGatewayExtensionServer.
type Server struct {
	pb.UnimplementedEnvoyGatewayExtensionServer

	// CertProviderTargetURI is the gRPC target the custom handshaker dials
	// to fetch leaf certs (e.g. "controller-manager.clrk.svc:9443" or
	// "localhost:9443" when the handshaker runs in-pod next to us).
	CertProviderTargetURI string

	// ExtProcTargetURI is the gRPC target for body-capture.
	ExtProcTargetURI string
}

// New constructs an extension server. The URIs are the gRPC addresses
// Envoy uses to reach the cert provider and ext_proc server (both hosted
// by the clrk controller-manager).
func New(certProviderURI, extProcURI string) *Server {
	return &Server{
		CertProviderTargetURI: certProviderURI,
		ExtProcTargetURI:      extProcURI,
	}
}

// PostHTTPListenerModify wires the MITM handshaker and ext_proc HTTP filter
// into every clrk-owned HTTP listener.
func (s *Server) PostHTTPListenerModify(ctx context.Context, req *pb.PostHTTPListenerModifyRequest) (*pb.PostHTTPListenerModifyResponse, error) {
	logger := ctrllog.FromContext(ctx).WithName("egextension")
	listener := req.GetListener()
	if listener == nil {
		return &pb.PostHTTPListenerModifyResponse{Listener: listener}, nil
	}

	egKey, ok := egressGatewayFromListener(listener)
	if !ok {
		return &pb.PostHTTPListenerModifyResponse{Listener: listener}, nil
	}

	logger.Info("Rewriting egress listener",
		"listener", listener.GetName(), "eg.namespace", egKey.namespace, "eg.name", egKey.name)

	allChains := listener.GetFilterChains()
	if defaultFC := listener.GetDefaultFilterChain(); defaultFC != nil {
		allChains = append(allChains, defaultFC)
	}

	for _, fc := range allChains {
		if err := s.injectHandshaker(fc, egKey); err != nil {
			logger.Error(err, "Inject handshaker failed", "filterChain", fc.GetName())
		}
		if err := s.injectExtProc(fc); err != nil {
			logger.Error(err, "Inject ext_proc failed", "filterChain", fc.GetName())
		}
	}

	return &pb.PostHTTPListenerModifyResponse{Listener: listener}, nil
}

// PostTranslateModify is a no-op for now; cluster and secret manipulation
// lives in the EgressGateway controller (via direct xDS patches to the
// EnvoyProxy bootstrap).
func (s *Server) PostTranslateModify(ctx context.Context, req *pb.PostTranslateModifyRequest) (*pb.PostTranslateModifyResponse, error) {
	return &pb.PostTranslateModifyResponse{
		Clusters: req.GetClusters(),
		Secrets:  req.GetSecrets(),
	}, nil
}

// PostRouteModify is a no-op.
func (s *Server) PostRouteModify(ctx context.Context, req *pb.PostRouteModifyRequest) (*pb.PostRouteModifyResponse, error) {
	return &pb.PostRouteModifyResponse{Route: req.GetRoute()}, nil
}

// PostVirtualHostModify is a no-op.
func (s *Server) PostVirtualHostModify(ctx context.Context, req *pb.PostVirtualHostModifyRequest) (*pb.PostVirtualHostModifyResponse, error) {
	return &pb.PostVirtualHostModifyResponse{VirtualHost: req.GetVirtualHost()}, nil
}

// egKey is a parsed (namespace, gatewayName) for an EgressGateway.
type egKey struct {
	namespace string
	name      string
}

// egressGatewayFromListener parses the EG namespace+name out of a listener
// name. EG names its listeners "<namespace>/<gatewayName>/<listenerName>".
// Our Gateway names follow GatewayNamePrefix so we can filter non-clrk
// listeners cleanly.
func egressGatewayFromListener(l *listenerv3.Listener) (egKey, bool) {
	parts := strings.Split(l.GetName(), "/")
	if len(parts) < 2 || parts[0] == "" {
		return egKey{}, false
	}
	if !strings.HasPrefix(parts[1], GatewayNamePrefix) {
		return egKey{}, false
	}
	return egKey{namespace: parts[0], name: strings.TrimPrefix(parts[1], GatewayNamePrefix)}, true
}

// injectHandshaker replaces the filter chain's DownstreamTlsContext custom
// handshaker with our grpc_certificate_provider. Filter chains without TLS
// (plain HTTP listeners) are skipped.
func (s *Server) injectHandshaker(fc *listenerv3.FilterChain, key egKey) error {
	ts := fc.GetTransportSocket()
	if ts == nil || ts.GetName() != tlsTransportSocketName {
		return nil
	}
	typedCfg := ts.GetTypedConfig()
	if typedCfg == nil {
		return nil
	}

	downstream := &tlsv3.DownstreamTlsContext{}
	if err := typedCfg.UnmarshalTo(downstream); err != nil {
		return fmt.Errorf("unmarshal DownstreamTlsContext: %w", err)
	}
	if downstream.CommonTlsContext == nil {
		downstream.CommonTlsContext = &tlsv3.CommonTlsContext{}
	}

	handshakerCfg := &tlsv3.GrpcCertificateProviderConfig{
		GrpcService: &corev3.GrpcService{
			TargetSpecifier: &corev3.GrpcService_GoogleGrpc_{
				GoogleGrpc: &corev3.GrpcService_GoogleGrpc{
					TargetUri:  s.CertProviderTargetURI,
					StatPrefix: "clrk_cert_provider",
				},
			},
			InitialMetadata: []*corev3.HeaderValue{
				{Key: certprovider.MetaKeyEgressGatewayNamespace, Value: key.namespace},
				{Key: certprovider.MetaKeyEgressGatewayName, Value: key.name},
			},
		},
		Timeout:         durationpb.New(defaultHandshakerTimeout),
		CacheTtl:        durationpb.New(defaultHandshakerCacheTTL),
		CacheMaxEntries: defaultHandshakerCacheMax,
		FailOnError:     true,
	}
	handshakerAny, err := anypb.New(handshakerCfg)
	if err != nil {
		return fmt.Errorf("marshal GrpcCertificateProviderConfig: %w", err)
	}
	downstream.CommonTlsContext.CustomHandshaker = &corev3.TypedExtensionConfig{
		Name:        grpcCertProviderHandshakerName,
		TypedConfig: handshakerAny,
	}

	newTypedCfg, err := anypb.New(downstream)
	if err != nil {
		return fmt.Errorf("re-marshal DownstreamTlsContext: %w", err)
	}
	ts.ConfigType = &corev3.TransportSocket_TypedConfig{TypedConfig: newTypedCfg}
	return nil
}

// injectExtProc prepends an ext_proc HTTP filter to every HCM in the
// filter chain, positioned right before the router filter so body capture
// runs after all routing/auth filters have executed.
func (s *Server) injectExtProc(fc *listenerv3.FilterChain) error {
	for _, f := range fc.GetFilters() {
		if f.GetName() != "envoy.filters.network.http_connection_manager" {
			continue
		}
		typedCfg := f.GetTypedConfig()
		if typedCfg == nil {
			continue
		}
		hcm := &hcmv3.HttpConnectionManager{}
		if err := typedCfg.UnmarshalTo(hcm); err != nil {
			return fmt.Errorf("unmarshal HCM: %w", err)
		}

		extProcCfg := &extprocv3.ExternalProcessor{
			GrpcService: &corev3.GrpcService{
				TargetSpecifier: &corev3.GrpcService_GoogleGrpc_{
					GoogleGrpc: &corev3.GrpcService_GoogleGrpc{
						TargetUri:  s.ExtProcTargetURI,
						StatPrefix: "clrk_ext_proc",
					},
				},
				Timeout: durationpb.New(defaultExtProcTimeout),
			},
			ProcessingMode: &extprocv3.ProcessingMode{
				RequestHeaderMode:   extprocv3.ProcessingMode_SEND,
				ResponseHeaderMode:  extprocv3.ProcessingMode_SEND,
				RequestBodyMode:     extprocv3.ProcessingMode_BUFFERED_PARTIAL,
				ResponseBodyMode:    extprocv3.ProcessingMode_BUFFERED_PARTIAL,
				RequestTrailerMode:  extprocv3.ProcessingMode_SKIP,
				ResponseTrailerMode: extprocv3.ProcessingMode_SKIP,
			},
			MetadataOptions: &extprocv3.MetadataOptions{
				ForwardingNamespaces: &extprocv3.MetadataOptions_MetadataNamespaces{
					Untyped: []string{"clrk.apoxy.dev"},
				},
			},
		}
		extProcAny, err := anypb.New(extProcCfg)
		if err != nil {
			return fmt.Errorf("marshal ext_proc config: %w", err)
		}

		// Insert the ext_proc filter immediately before the router filter.
		filter := &hcmv3.HttpFilter{
			Name:       extProcFilterName,
			ConfigType: &hcmv3.HttpFilter_TypedConfig{TypedConfig: extProcAny},
		}
		inserted := false
		newFilters := make([]*hcmv3.HttpFilter, 0, len(hcm.HttpFilters)+1)
		for _, existing := range hcm.HttpFilters {
			if existing.GetName() == routerFilterName && !inserted {
				newFilters = append(newFilters, filter)
				inserted = true
			}
			newFilters = append(newFilters, existing)
		}
		if !inserted {
			newFilters = append(newFilters, filter)
		}
		hcm.HttpFilters = newFilters

		newTypedCfg, err := anypb.New(hcm)
		if err != nil {
			return fmt.Errorf("re-marshal HCM: %w", err)
		}
		f.ConfigType = &listenerv3.Filter_TypedConfig{TypedConfig: newTypedCfg}
	}
	return nil
}
