// Package egextension implements the Envoy Gateway extension server that
// rewrites xDS resources on the way out of EG's translator. We use it for
// two things:
//
//  1. Inject the grpc_certificate_provider custom handshaker onto every
//     egress listener's DownstreamTlsContext, with initial gRPC metadata
//     scoping the cert-provider lookup to the right EgressGateway.
//  2. Append an ext_proc HTTP filter to every HCM filter chain so body
//     capture lands on the clrk controller-manager's ext_proc service.
//
// Only listeners generated by clrk-owned Gateways should pass through
// here: clrk's EgressGateway controller creates Gateways with names of
// the form "clrk-eg-<egName>" under a dedicated GatewayClass, and the
// EnvoyProxy attached to that GatewayClass points at this extension. If
// the extension sees a listener that does not match that naming
// convention it leaves it untouched.
package egextension

import (
	"context"
	"fmt"
	"strings"
	"time"

	clusterv3 "github.com/envoyproxy/go-control-plane/envoy/config/cluster/v3"
	corev3 "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
	listenerv3 "github.com/envoyproxy/go-control-plane/envoy/config/listener/v3"
	routev3 "github.com/envoyproxy/go-control-plane/envoy/config/route/v3"
	dfpclusterv3 "github.com/envoyproxy/go-control-plane/envoy/extensions/clusters/dynamic_forward_proxy/v3"
	dfpcommonv3 "github.com/envoyproxy/go-control-plane/envoy/extensions/common/dynamic_forward_proxy/v3"
	dfpfilterv3 "github.com/envoyproxy/go-control-plane/envoy/extensions/filters/http/dynamic_forward_proxy/v3"
	extprocv3 "github.com/envoyproxy/go-control-plane/envoy/extensions/filters/http/ext_proc/v3"
	proxyprotov3 "github.com/envoyproxy/go-control-plane/envoy/extensions/filters/listener/proxy_protocol/v3"
	tlsinspectorv3 "github.com/envoyproxy/go-control-plane/envoy/extensions/filters/listener/tls_inspector/v3"
	netextprocv3 "github.com/envoyproxy/go-control-plane/envoy/extensions/filters/network/ext_proc/v3"
	hcmv3 "github.com/envoyproxy/go-control-plane/envoy/extensions/filters/network/http_connection_manager/v3"
	snidfpv3 "github.com/envoyproxy/go-control-plane/envoy/extensions/filters/network/sni_dynamic_forward_proxy/v3"
	tcpproxyv3 "github.com/envoyproxy/go-control-plane/envoy/extensions/filters/network/tcp_proxy/v3"
	pb "github.com/envoyproxy/gateway/proto/extension"
	"google.golang.org/protobuf/types/known/anypb"
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/wrapperspb"
	ctrllog "sigs.k8s.io/controller-runtime/pkg/log"

	tlsv3 "github.com/apoxy-dev/envoy-go/envoy/extensions/transport_sockets/tls/v3"

	"github.com/apoxy-dev/clrk/internal/egidentity"
	"github.com/apoxy-dev/clrk/internal/egress/proxyproto"
	"github.com/apoxy-dev/clrk/internal/extproc"
	"k8s.io/apimachinery/pkg/types"
)

// Well-known extension names.
const (
	grpcCertProviderHandshakerName = "envoy.tls_handshakers.grpc_certificate_provider"
	extProcFilterName              = "envoy.filters.http.ext_proc"
	routerFilterName               = "envoy.filters.http.router"
	tlsTransportSocketName         = "envoy.transport_sockets.tls"
	hcmFilterName                  = "envoy.filters.network.http_connection_manager"

	proxyProtocolListenerFilterName = "envoy.filters.listener.proxy_protocol"
	tlsInspectorListenerFilterName  = "envoy.filters.listener.tls_inspector"
	dfpHTTPFilterName               = "envoy.filters.http.dynamic_forward_proxy"

	networkExtProcFilterName = "envoy.filters.network.ext_proc"
	sniDFPFilterName         = "envoy.filters.network.sni_dynamic_forward_proxy"
	tcpProxyFilterName       = "envoy.filters.network.tcp_proxy"

	// tcpFallbackChainName identifies the synthesized TCP-fallback
	// filter chain (non-HTTP TLS protocols) on each egress listener.
	// Doubles as an idempotency marker so repeat
	// PostHTTPListenerModify calls don't duplicate the chain.
	tcpFallbackChainName = "clrk-egress-tcp-fallback"

	// DFPClusterName is the synthetic dynamic_forward_proxy cluster name
	// PostHTTPListenerModify routes to and PostTranslateModify creates.
	DFPClusterName = "clrk-egress-dfp"

	// dnsCacheName ties the dynamic_forward_proxy HTTP filter and cluster
	// to the same DNS cache instance.
	dnsCacheName = "clrk-egress-dns-cache"
)

// httpALPNs are the application protocol names the existing HTTP
// chain narrows to once the TCP-fallback chain lands. Connections
// that advertise either ALPN claim the HTTP chain; everything else
// falls through to the default (no-FCM) TCP-fallback chain.
var httpALPNs = []string{"h2", "http/1.1"}

// agentTLVRules maps each clrk PROXY v2 TLV type into a dynamic-metadata
// entry the proxy_protocol listener filter publishes. ext_proc reads them
// back from MetadataContext under the same namespace.
var agentTLVRules = []*proxyprotov3.ProxyProtocol_Rule{
	tlvRule(proxyproto.TLVAgentKind, extproc.MetaAgentKind),
	tlvRule(proxyproto.TLVAgentNamespace, extproc.MetaAgentNamespace),
	tlvRule(proxyproto.TLVAgentName, extproc.MetaAgentName),
	tlvRule(proxyproto.TLVAgentUID, extproc.MetaAgentUID),
	tlvRule(proxyproto.TLVAgentRevision, extproc.MetaAgentRevision),
	tlvRule(proxyproto.TLVInvocationID, extproc.MetaInvocationID),
}

func tlvRule(t byte, key string) *proxyprotov3.ProxyProtocol_Rule {
	return &proxyprotov3.ProxyProtocol_Rule{
		TlvType: uint32(t),
		OnTlvPresent: &proxyprotov3.ProxyProtocol_KeyValuePair{
			MetadataNamespace: extproc.MetadataNamespace,
			Key:               key,
		},
	}
}

// dnsCacheConfig is shared by the dynamic_forward_proxy HTTP filter and the
// matching cluster — both must reference the same Name to share an Envoy
// DNS cache instance, so the proto is a pre-built singleton.
var dnsCacheConfig = &dfpcommonv3.DnsCacheConfig{
	Name:            dnsCacheName,
	DnsLookupFamily: clusterv3.Cluster_AUTO,
}

// GatewayNamePrefix is the prefix the EgressGateway controller uses when
// creating Gateway resources. We parse it off listener names so every
// other Gateway (ingress etc.) is left alone.
const GatewayNamePrefix = "clrk-eg-"

const (
	defaultHandshakerTimeout  = 60 * time.Second
	defaultHandshakerCacheTTL = 1 * time.Hour
	defaultHandshakerCacheMax = 1000

	defaultExtProcTimeout = 30 * time.Second
)

// Server implements envoyproxy/gateway extension.EnvoyGatewayExtensionServer.
// Register with a gRPC server via pb.RegisterEnvoyGatewayExtensionServer.
type Server struct {
	pb.UnimplementedEnvoyGatewayExtensionServer

	// CertProviderTargetURI is the gRPC target the custom handshaker dials
	// to fetch leaf certs (e.g. "controller-manager.clrk.svc:9443" or
	// "localhost:9443" when the handshaker runs in-pod next to us).
	CertProviderTargetURI string

	// ExtProcTargetURI is the gRPC target for body-capture.
	ExtProcTargetURI string

	// dfpHTTPFilter and dfpCluster are pre-built — their proto contents
	// don't vary across listeners. The ext_proc filter is rebuilt per
	// listener because it carries a per-EG :authority value that
	// identifies the calling EG to the controller-manager.
	dfpHTTPFilter *hcmv3.HttpFilter
	dfpCluster    *clusterv3.Cluster
}

// New constructs an extension server. The URIs are the gRPC addresses
// Envoy uses to reach the cert provider and ext_proc server (both hosted
// by the clrk controller-manager).
func New(certProviderURI, extProcURI string) (*Server, error) {
	dfp, err := buildDFPHTTPFilter()
	if err != nil {
		return nil, err
	}
	cluster, err := buildDFPCluster()
	if err != nil {
		return nil, err
	}
	return &Server{
		CertProviderTargetURI: certProviderURI,
		ExtProcTargetURI:      extProcURI,
		dfpHTTPFilter:         dfp,
		dfpCluster:            cluster,
	}, nil
}

// PostHTTPListenerModify rewrites every clrk-owned egress listener so that:
//
//   - PROXY v2 framing is decoded off the wire and TLV agent identity is
//     surfaced as dynamic metadata under the clrk.apoxy.dev namespace.
//   - The TLS ClientHello is parsed so the handshaker can mint an SNI-keyed
//     leaf cert against the per-EG CA.
//   - Each filter chain's DownstreamTlsContext uses our gRPC certificate
//     provider handshaker, so leaves come from controller-manager.
//   - Each HCM gains the dynamic_forward_proxy + ext_proc HTTP filters and
//     a single virtual_host * route to the synthetic DFP cluster created
//     by PostTranslateModify.
func (s *Server) PostHTTPListenerModify(ctx context.Context, req *pb.PostHTTPListenerModifyRequest) (*pb.PostHTTPListenerModifyResponse, error) {
	logger := ctrllog.FromContext(ctx).WithName("egextension")
	listener := req.GetListener()
	if listener == nil {
		return &pb.PostHTTPListenerModifyResponse{Listener: listener}, nil
	}

	egKey, ok := egressGatewayFromListener(listener)
	if !ok {
		return &pb.PostHTTPListenerModifyResponse{Listener: listener}, nil
	}

	logger.Info("Rewriting egress listener",
		"listener", listener.GetName(), "eg.namespace", egKey.namespace, "eg.name", egKey.name)

	if err := ensureListenerFilters(listener); err != nil {
		logger.Error(err, "Adding listener filters failed", "listener", listener.GetName())
	}

	allChains := listener.GetFilterChains()
	if defaultFC := listener.GetDefaultFilterChain(); defaultFC != nil {
		allChains = append(allChains, defaultFC)
	}

	for _, fc := range allChains {
		if err := s.injectHandshaker(fc, egKey); err != nil {
			logger.Error(err, "Inject handshaker failed", "filterChain", fc.GetName())
		}
		if fc.GetName() == tcpFallbackChainName {
			// The TCP-fallback chain doesn't carry an HCM; rewriteHCM
			// would no-op on it but skipping is cheaper and explicit.
			continue
		}
		if err := s.rewriteHCM(fc, egKey); err != nil {
			logger.Error(err, "Rewrite HCM failed", "filterChain", fc.GetName())
		}
	}

	// Narrow each existing chain to advertise HTTP ALPNs only and append
	// a single default TCP-fallback chain. tls_inspector reads ALPN from
	// the ClientHello before chain matching, so HTTP-ALPN connections
	// claim the HTTP chain and everything else (no ALPN, postgresql,
	// mongodb, grpc-exp, etc.) falls through. Idempotent: repeat
	// PostHTTPListenerModify calls leave the listener unchanged.
	if !hasTCPFallbackChain(listener) {
		for _, fc := range listener.GetFilterChains() {
			narrowChainToHTTPALPNs(fc)
		}
		fallback, err := s.buildTCPFallbackChain(listener.GetFilterChains(), egKey)
		if err != nil {
			logger.Error(err, "Build TCP-fallback chain failed", "listener", listener.GetName())
		} else if fallback != nil {
			listener.FilterChains = append(listener.FilterChains, fallback)
		}
	}

	return &pb.PostHTTPListenerModifyResponse{Listener: listener}, nil
}

// PostTranslateModify appends a synthetic dynamic_forward_proxy cluster
// (DFPClusterName) so the HCM route action injected by
// PostHTTPListenerModify has a concrete cluster to route to. The HTTP
// filter and the cluster share a single DNS cache configuration so SNI
// → upstream resolution is consistent.
func (s *Server) PostTranslateModify(ctx context.Context, req *pb.PostTranslateModifyRequest) (*pb.PostTranslateModifyResponse, error) {
	in := req.GetClusters()
	out := append(make([]*clusterv3.Cluster, 0, len(in)+1), s.dfpCluster)
	for _, c := range in {
		if c.GetName() != DFPClusterName {
			out = append(out, c)
		}
	}
	return &pb.PostTranslateModifyResponse{
		Clusters: out,
		Secrets:  req.GetSecrets(),
	}, nil
}

// PostRouteModify is a no-op.
func (s *Server) PostRouteModify(ctx context.Context, req *pb.PostRouteModifyRequest) (*pb.PostRouteModifyResponse, error) {
	return &pb.PostRouteModifyResponse{Route: req.GetRoute()}, nil
}

// PostVirtualHostModify is a no-op.
func (s *Server) PostVirtualHostModify(ctx context.Context, req *pb.PostVirtualHostModifyRequest) (*pb.PostVirtualHostModifyResponse, error) {
	return &pb.PostVirtualHostModifyResponse{VirtualHost: req.GetVirtualHost()}, nil
}

// egKey is a parsed (namespace, gatewayName) for an EgressGateway.
type egKey struct {
	namespace string
	name      string
}

// egressGatewayFromListener parses the EG namespace+name out of a listener
// name. EG names its listeners "<namespace>/<gatewayName>/<listenerName>".
// Our Gateway names follow GatewayNamePrefix so we can filter non-clrk
// listeners cleanly.
func egressGatewayFromListener(l *listenerv3.Listener) (egKey, bool) {
	parts := strings.Split(l.GetName(), "/")
	if len(parts) < 2 || parts[0] == "" {
		return egKey{}, false
	}
	if !strings.HasPrefix(parts[1], GatewayNamePrefix) {
		return egKey{}, false
	}
	return egKey{namespace: parts[0], name: strings.TrimPrefix(parts[1], GatewayNamePrefix)}, true
}

// injectHandshaker replaces the filter chain's DownstreamTlsContext custom
// handshaker with our grpc_certificate_provider. Filter chains without TLS
// (plain HTTP listeners) are skipped.
func (s *Server) injectHandshaker(fc *listenerv3.FilterChain, key egKey) error {
	ts := fc.GetTransportSocket()
	if ts == nil || ts.GetName() != tlsTransportSocketName {
		return nil
	}
	typedCfg := ts.GetTypedConfig()
	if typedCfg == nil {
		return nil
	}

	downstream := &tlsv3.DownstreamTlsContext{}
	if err := typedCfg.UnmarshalTo(downstream); err != nil {
		return fmt.Errorf("unmarshal DownstreamTlsContext: %w", err)
	}
	if downstream.CommonTlsContext == nil {
		downstream.CommonTlsContext = &tlsv3.CommonTlsContext{}
	}

	// The stock grpc_certificate_provider handshaker forwards only the
	// SNI to FetchCertificate; GrpcService.InitialMetadata is dropped.
	// We use the apoxy fork's `authority` field instead, which the
	// patched handshaker wires through grpc::ClientContext::set_authority
	// per call. The controller-manager's gRPC interceptor parses
	// :authority off incoming metadata and resolves the calling EG from
	// it — no peer-IP introspection, works under NAT and with N EGs.
	authority := egidentity.AuthorityFor(types.NamespacedName{
		Namespace: key.namespace,
		Name:      key.name,
	})
	handshakerCfg := &tlsv3.GrpcCertificateProviderConfig{
		GrpcService: &corev3.GrpcService{
			TargetSpecifier: &corev3.GrpcService_GoogleGrpc_{
				GoogleGrpc: &corev3.GrpcService_GoogleGrpc{
					TargetUri:  s.CertProviderTargetURI,
					StatPrefix: "clrk_cert_provider",
				},
			},
		},
		Timeout:         durationpb.New(defaultHandshakerTimeout),
		CacheTtl:        durationpb.New(defaultHandshakerCacheTTL),
		CacheMaxEntries: defaultHandshakerCacheMax,
		FailOnError:     true,
		Authority:       authority,
	}
	handshakerAny, err := anypb.New(handshakerCfg)
	if err != nil {
		return fmt.Errorf("marshal GrpcCertificateProviderConfig: %w", err)
	}
	downstream.CommonTlsContext.CustomHandshaker = &corev3.TypedExtensionConfig{
		Name:        grpcCertProviderHandshakerName,
		TypedConfig: handshakerAny,
	}

	newTypedCfg, err := anypb.New(downstream)
	if err != nil {
		return fmt.Errorf("re-marshal DownstreamTlsContext: %w", err)
	}
	ts.ConfigType = &corev3.TransportSocket_TypedConfig{TypedConfig: newTypedCfg}
	return nil
}

// rewriteHCM replaces every HCM in the filter chain with an MITM-shaped
// configuration: prepends the dynamic_forward_proxy and ext_proc HTTP
// filters before the router, and replaces any baked-in route_config with
// a single virtual_host * route to the synthetic DFPClusterName cluster
// (auto_host_rewrite so the upstream Host comes from :authority).
//
// The ext_proc filter is rebuilt per call because it carries a per-EG
// :authority value that identifies the calling EG to the
// controller-manager.
func (s *Server) rewriteHCM(fc *listenerv3.FilterChain, key egKey) error {
	extProcFilter, err := buildExtProcFilter(s.ExtProcTargetURI, egidentity.AuthorityFor(types.NamespacedName{
		Namespace: key.namespace,
		Name:      key.name,
	}))
	if err != nil {
		return fmt.Errorf("build ext_proc filter: %w", err)
	}
	for _, f := range fc.GetFilters() {
		if f.GetName() != hcmFilterName {
			continue
		}
		typedCfg := f.GetTypedConfig()
		if typedCfg == nil {
			continue
		}
		hcm := &hcmv3.HttpConnectionManager{}
		if err := typedCfg.UnmarshalTo(hcm); err != nil {
			return fmt.Errorf("unmarshal HCM: %w", err)
		}

		// Filter order: ext_proc (captures req+resp, also rewrites
		// :authority to add :443 when the request omitted the implicit
		// HTTPS port), DFP (parses host:port off the rewritten
		// authority for upstream selection), router (terminal). The
		// ext_proc → DFP order is what lets us fold the port fixup
		// into our own gRPC handler instead of needing a separate Lua
		// filter. Anything EG put before router is preserved upstream
		// of these — drop nothing the operator configured (auth,
		// ratelimit, etc.) but make sure ours land just before router
		// so they always run.
		ours := []*hcmv3.HttpFilter{extProcFilter, s.dfpHTTPFilter}
		newFilters := make([]*hcmv3.HttpFilter, 0, len(hcm.HttpFilters)+len(ours))
		inserted := false
		for _, existing := range hcm.HttpFilters {
			if existing.GetName() == routerFilterName && !inserted {
				newFilters = append(newFilters, ours...)
				inserted = true
			}
			newFilters = append(newFilters, existing)
		}
		if !inserted {
			newFilters = append(newFilters, ours...)
		}
		hcm.HttpFilters = newFilters

		// Replace whatever EG generated with a single catch-all
		// virtual_host that hands the request to the DFP cluster. Any
		// upstream rewrite happens via auto_host_rewrite; the SNI used
		// during MITM is also propagated as :authority so the upstream
		// connection re-resolves the original hostname.
		hcm.RouteSpecifier = &hcmv3.HttpConnectionManager_RouteConfig{
			RouteConfig: &routev3.RouteConfiguration{
				Name: "clrk-egress-dfp",
				VirtualHosts: []*routev3.VirtualHost{{
					Name:    "clrk-egress-dfp",
					Domains: []string{"*"},
					Routes: []*routev3.Route{{
						Match: &routev3.RouteMatch{
							PathSpecifier: &routev3.RouteMatch_Prefix{Prefix: "/"},
						},
						Action: &routev3.Route_Route{
							Route: &routev3.RouteAction{
								ClusterSpecifier: &routev3.RouteAction_Cluster{
									Cluster: DFPClusterName,
								},
								HostRewriteSpecifier: &routev3.RouteAction_AutoHostRewrite{
									AutoHostRewrite: wrapperspb.Bool(true),
								},
							},
						},
					}},
				}},
			},
		}

		newTypedCfg, err := anypb.New(hcm)
		if err != nil {
			return fmt.Errorf("re-marshal HCM: %w", err)
		}
		f.ConfigType = &listenerv3.Filter_TypedConfig{TypedConfig: newTypedCfg}
	}
	return nil
}

// ensureListenerFilters prepends the proxy_protocol and tls_inspector
// listener filters in that order. proxy_protocol must run first since the
// PROXY v2 frame precedes the TLS ClientHello on the wire. Idempotent —
// skips filters already present (matched by name).
func ensureListenerFilters(l *listenerv3.Listener) error {
	have := make(map[string]bool, len(l.GetListenerFilters()))
	for _, lf := range l.GetListenerFilters() {
		have[lf.GetName()] = true
	}

	var prepend []*listenerv3.ListenerFilter

	if !have[proxyProtocolListenerFilterName] {
		ppCfg := &proxyprotov3.ProxyProtocol{Rules: agentTLVRules}
		ppAny, err := anypb.New(ppCfg)
		if err != nil {
			return fmt.Errorf("marshal proxy_protocol: %w", err)
		}
		prepend = append(prepend, &listenerv3.ListenerFilter{
			Name: proxyProtocolListenerFilterName,
			ConfigType: &listenerv3.ListenerFilter_TypedConfig{
				TypedConfig: ppAny,
			},
		})
	}
	if !have[tlsInspectorListenerFilterName] {
		insp, err := anypb.New(&tlsinspectorv3.TlsInspector{})
		if err != nil {
			return fmt.Errorf("marshal tls_inspector: %w", err)
		}
		prepend = append(prepend, &listenerv3.ListenerFilter{
			Name: tlsInspectorListenerFilterName,
			ConfigType: &listenerv3.ListenerFilter_TypedConfig{
				TypedConfig: insp,
			},
		})
	}

	if len(prepend) > 0 {
		l.ListenerFilters = append(prepend, l.GetListenerFilters()...)
	}
	return nil
}

// hasTCPFallbackChain reports whether listener already carries the
// synthesized TCP-fallback chain. Match by chain name so the marker
// survives controller restarts that re-translate the same Gateway.
func hasTCPFallbackChain(l *listenerv3.Listener) bool {
	for _, fc := range l.GetFilterChains() {
		if fc.GetName() == tcpFallbackChainName {
			return true
		}
	}
	return false
}

// narrowChainToHTTPALPNs adds httpALPNs to fc.FilterChainMatch.
// Idempotent — leaves the slice alone when both ALPNs are already
// present. Other ApplicationProtocols entries are preserved (in case
// EG ever populates them itself).
func narrowChainToHTTPALPNs(fc *listenerv3.FilterChain) {
	if fc.FilterChainMatch == nil {
		fc.FilterChainMatch = &listenerv3.FilterChainMatch{}
	}
	have := make(map[string]bool, len(fc.FilterChainMatch.ApplicationProtocols))
	for _, p := range fc.FilterChainMatch.ApplicationProtocols {
		have[p] = true
	}
	for _, p := range httpALPNs {
		if !have[p] {
			fc.FilterChainMatch.ApplicationProtocols = append(fc.FilterChainMatch.ApplicationProtocols, p)
			have[p] = true
		}
	}
}

// buildTCPFallbackChain assembles the catch-all chain that handles
// non-HTTP TLS connections (Postgres direct SSL, MongoDB direct TLS,
// gRPC-TLS, etc.). The chain shares downstream TLS termination with
// the HTTP chain — same per-EG CA, same gRPC handshaker — but
// substitutes a network-level filter list:
//
//  1. network_ext_proc: streams agent-direction bytes to the L4
//     ext_proc server with PV2 agent identity attached as
//     dynamic_metadata. Observe-only at MVP (handler returns
//     UNMODIFIED + CONTINUE on every chunk).
//  2. sni_dynamic_forward_proxy: stamps the ClientHello SNI as the
//     upstream host the DFP cluster resolves.
//  3. tcp_proxy: forwards to the shared DFPClusterName cluster.
//
// Returns nil when the listener has no chain to clone the
// transport_socket from (would mean a non-TLS listener — clrk
// listeners are always TLS).
func (s *Server) buildTCPFallbackChain(httpChains []*listenerv3.FilterChain, key egKey) (*listenerv3.FilterChain, error) {
	var template *listenerv3.FilterChain
	for _, fc := range httpChains {
		if fc.GetTransportSocket() != nil {
			template = fc
			break
		}
	}
	if template == nil {
		return nil, nil
	}

	netExtProc, err := buildNetworkExtProcFilter(s.ExtProcTargetURI, egidentity.AuthorityFor(types.NamespacedName{
		Namespace: key.namespace,
		Name:      key.name,
	}))
	if err != nil {
		return nil, fmt.Errorf("build network_ext_proc filter: %w", err)
	}
	sniDFP, err := buildSNIDFPFilter()
	if err != nil {
		return nil, fmt.Errorf("build sni_dynamic_forward_proxy filter: %w", err)
	}
	tcpProxy, err := buildTCPProxyFilter()
	if err != nil {
		return nil, fmt.Errorf("build tcp_proxy filter: %w", err)
	}

	return &listenerv3.FilterChain{
		Name:            tcpFallbackChainName,
		TransportSocket: template.GetTransportSocket(),
		Filters:         []*listenerv3.Filter{netExtProc, sniDFP, tcpProxy},
	}, nil
}

// buildNetworkExtProcFilter builds the L4 ext_proc filter. Mirrors
// buildExtProcFilter (HTTP) on the gRPC + authority + metadata-
// forwarding wiring; the ProcessingMode differs (no header / body
// modes — those are HTTP-only fields). ProcessRead = STREAMED and
// ProcessWrite = SKIP: the filter rejects SKIP/SKIP, and observing
// the agent-direction (read) path is the audit-relevant direction.
func buildNetworkExtProcFilter(targetURI, authority string) (*listenerv3.Filter, error) {
	any, err := anypb.New(&netextprocv3.NetworkExternalProcessor{
		GrpcService: &corev3.GrpcService{
			TargetSpecifier: &corev3.GrpcService_GoogleGrpc_{
				GoogleGrpc: &corev3.GrpcService_GoogleGrpc{
					TargetUri:  targetURI,
					StatPrefix: "clrk_l4_ext_proc",
					ChannelArgs: &corev3.GrpcService_GoogleGrpc_ChannelArgs{
						Args: map[string]*corev3.GrpcService_GoogleGrpc_ChannelArgs_Value{
							"grpc.default_authority": {
								ValueSpecifier: &corev3.GrpcService_GoogleGrpc_ChannelArgs_Value_StringValue{
									StringValue: authority,
								},
							},
						},
					},
				},
			},
			Timeout: durationpb.New(defaultExtProcTimeout),
		},
		FailureModeAllow: true,
		ProcessingMode: &netextprocv3.ProcessingMode{
			ProcessRead:  netextprocv3.ProcessingMode_STREAMED,
			ProcessWrite: netextprocv3.ProcessingMode_SKIP,
		},
		MessageTimeout: durationpb.New(5 * time.Second),
		StatPrefix:     "clrk_l4_ext_proc",
		MetadataOptions: &netextprocv3.MetadataOptions{
			ForwardingNamespaces: &netextprocv3.MetadataOptions_MetadataNamespaces{
				Untyped: []string{extproc.MetadataNamespace},
			},
		},
	})
	if err != nil {
		return nil, fmt.Errorf("marshal network_ext_proc: %w", err)
	}
	return &listenerv3.Filter{
		Name:       networkExtProcFilterName,
		ConfigType: &listenerv3.Filter_TypedConfig{TypedConfig: any},
	}, nil
}

// buildSNIDFPFilter builds the sni_dynamic_forward_proxy network
// filter. Reads SNI off the connection and stamps it as the
// upstream host the DFP cluster resolves; uses the same DNS cache
// as the HTTP path so dual-protocol upstreams (HTTPS + native TLS)
// share resolution.
func buildSNIDFPFilter() (*listenerv3.Filter, error) {
	any, err := anypb.New(&snidfpv3.FilterConfig{
		PortSpecifier: &snidfpv3.FilterConfig_PortValue{PortValue: 443},
		DnsCacheConfig: dnsCacheConfig,
	})
	if err != nil {
		return nil, fmt.Errorf("marshal sni_dynamic_forward_proxy: %w", err)
	}
	return &listenerv3.Filter{
		Name:       sniDFPFilterName,
		ConfigType: &listenerv3.Filter_TypedConfig{TypedConfig: any},
	}, nil
}

// buildTCPProxyFilter builds the terminal tcp_proxy filter pointing
// at the shared DFPClusterName cluster.
func buildTCPProxyFilter() (*listenerv3.Filter, error) {
	any, err := anypb.New(&tcpproxyv3.TcpProxy{
		StatPrefix: "clrk_egress_tcp",
		ClusterSpecifier: &tcpproxyv3.TcpProxy_Cluster{
			Cluster: DFPClusterName,
		},
	})
	if err != nil {
		return nil, fmt.Errorf("marshal tcp_proxy: %w", err)
	}
	return &listenerv3.Filter{
		Name:       tcpProxyFilterName,
		ConfigType: &listenerv3.Filter_TypedConfig{TypedConfig: any},
	}, nil
}

// buildDFPHTTPFilter returns the dynamic_forward_proxy HTTP filter that
// resolves the request's :authority through the shared DNS cache.
func buildDFPHTTPFilter() (*hcmv3.HttpFilter, error) {
	any, err := anypb.New(&dfpfilterv3.FilterConfig{
		ImplementationSpecifier: &dfpfilterv3.FilterConfig_DnsCacheConfig{
			DnsCacheConfig: dnsCacheConfig,
		},
	})
	if err != nil {
		return nil, fmt.Errorf("marshal dfp http filter: %w", err)
	}
	return &hcmv3.HttpFilter{
		Name:       dfpHTTPFilterName,
		ConfigType: &hcmv3.HttpFilter_TypedConfig{TypedConfig: any},
	}, nil
}

// buildExtProcFilter constructs the per-listener ext_proc HTTP filter.
// The synthetic authority is plumbed through grpc.default_authority so
// every FetchCertificate / ext_proc gRPC call advertises the EG identity
// on the HTTP/2 :authority pseudo-header. The controller-manager's
// gRPC interceptor parses :authority and looks up the calling EG.
//
// Stock GoogleGrpc has no first-class authority field, but Envoy's
// async client factory honors channel_args (see
// source/common/grpc/google_async_client_impl.cc) — the
// `grpc.default_authority` arg overrides the channel-default authority
// derived from target_uri.
func buildExtProcFilter(targetURI, authority string) (*hcmv3.HttpFilter, error) {
	any, err := anypb.New(&extprocv3.ExternalProcessor{
		GrpcService: &corev3.GrpcService{
			TargetSpecifier: &corev3.GrpcService_GoogleGrpc_{
				GoogleGrpc: &corev3.GrpcService_GoogleGrpc{
					TargetUri:  targetURI,
					StatPrefix: "clrk_ext_proc",
					ChannelArgs: &corev3.GrpcService_GoogleGrpc_ChannelArgs{
						Args: map[string]*corev3.GrpcService_GoogleGrpc_ChannelArgs_Value{
							"grpc.default_authority": {
								ValueSpecifier: &corev3.GrpcService_GoogleGrpc_ChannelArgs_Value_StringValue{
									StringValue: authority,
								},
							},
						},
					},
				},
			},
			Timeout: durationpb.New(defaultExtProcTimeout),
		},
		ProcessingMode: &extprocv3.ProcessingMode{
			RequestHeaderMode:   extprocv3.ProcessingMode_SEND,
			ResponseHeaderMode:  extprocv3.ProcessingMode_SEND,
			RequestBodyMode:     extprocv3.ProcessingMode_BUFFERED_PARTIAL,
			ResponseBodyMode:    extprocv3.ProcessingMode_BUFFERED_PARTIAL,
			RequestTrailerMode:  extprocv3.ProcessingMode_SKIP,
			ResponseTrailerMode: extprocv3.ProcessingMode_SKIP,
		},
		// Per-message timeout. Default is 200ms, which is too tight: on
		// the first stream after a sink-registry rebuild the handler does
		// a List(CIP)+List(APR)+per-CIP Secret Get, which can run past
		// 200ms on a cold informer cache. 5s gives slack without papering
		// over a real handler hang.
		MessageTimeout: durationpb.New(5 * time.Second),
		MetadataOptions: &extprocv3.MetadataOptions{
			ForwardingNamespaces: &extprocv3.MetadataOptions_MetadataNamespaces{
				Untyped: []string{extproc.MetadataNamespace},
			},
		},
	})
	if err != nil {
		return nil, fmt.Errorf("marshal ext_proc filter: %w", err)
	}
	return &hcmv3.HttpFilter{
		Name:       extProcFilterName,
		ConfigType: &hcmv3.HttpFilter_TypedConfig{TypedConfig: any},
	}, nil
}

// buildDFPCluster constructs the synthetic DFP cluster the HCM route_config
// targets. Uses the same DNS cache as the HTTP filter so resolution is
// shared. Always speaks TLS upstream — the EG terminates the sandbox's
// TLS at our MITM listener, so without re-encrypting we'd send plaintext
// to public origins (e.g. Cloudflare-fronted api.openai.com), which they
// reject with 403. SNI is taken from the per-request Host header, and
// upstream certs are verified against the envoy image's system trust
// bundle.
func buildDFPCluster() (*clusterv3.Cluster, error) {
	dfpAny, err := anypb.New(&dfpclusterv3.ClusterConfig{
		ClusterImplementationSpecifier: &dfpclusterv3.ClusterConfig_DnsCacheConfig{
			DnsCacheConfig: dnsCacheConfig,
		},
	})
	if err != nil {
		return nil, fmt.Errorf("marshal dfp cluster: %w", err)
	}

	tlsCtx := &tlsv3.UpstreamTlsContext{
		// Derive SNI from the upstream host. Envoy strips the port from
		// :authority before using it as the SNI value, so the ext_proc
		// :authority→host:443 rewrite doesn't leak ":443" into the TLS
		// ClientHello.
		AutoHostSni: true,
		CommonTlsContext: &tlsv3.CommonTlsContext{
			ValidationContextType: &tlsv3.CommonTlsContext_ValidationContext{
				ValidationContext: &tlsv3.CertificateValidationContext{
					TrustedCa: &corev3.DataSource{
						Specifier: &corev3.DataSource_Filename{
							// System trust bundle present in the
							// envoyproxy/envoy image (alpine-based).
							Filename: "/etc/ssl/certs/ca-certificates.crt",
						},
					},
				},
			},
		},
	}
	tlsAny, err := anypb.New(tlsCtx)
	if err != nil {
		return nil, fmt.Errorf("marshal upstream TLS context: %w", err)
	}

	return &clusterv3.Cluster{
		Name:           DFPClusterName,
		ConnectTimeout: durationpb.New(5 * time.Second),
		LbPolicy:       clusterv3.Cluster_CLUSTER_PROVIDED,
		ClusterDiscoveryType: &clusterv3.Cluster_ClusterType{
			ClusterType: &clusterv3.Cluster_CustomClusterType{
				Name:        "envoy.clusters.dynamic_forward_proxy",
				TypedConfig: dfpAny,
			},
		},
		TransportSocket: &corev3.TransportSocket{
			Name:       tlsTransportSocketName,
			ConfigType: &corev3.TransportSocket_TypedConfig{TypedConfig: tlsAny},
		},
	}, nil
}
