/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	http "net/http"

	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	scheme "github.com/apoxy-dev/clrk/client/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type ClrkV1alpha1Interface interface {
	RESTClient() rest.Interface
	AIProviderRoutesGetter
	AgentSandboxRevisionsGetter
	BackendsGetter
	CredentialInjectionPoliciesGetter
	DaemonAgentsGetter
	EgressDenyPoliciesGetter
	EgressGatewaysGetter
	EgressL4RoutesGetter
	FallbackRoutingPoliciesGetter
	InvocationsGetter
	LoggingPoliciesGetter
	MCPRoutesGetter
	RateLimitPoliciesGetter
	TaskAgentsGetter
	WorkerPoolsGetter
}

// ClrkV1alpha1Client is used to interact with features provided by the clrk.apoxy.dev group.
type ClrkV1alpha1Client struct {
	restClient rest.Interface
}

func (c *ClrkV1alpha1Client) AIProviderRoutes(namespace string) AIProviderRouteInterface {
	return newAIProviderRoutes(c, namespace)
}

func (c *ClrkV1alpha1Client) AgentSandboxRevisions(namespace string) AgentSandboxRevisionInterface {
	return newAgentSandboxRevisions(c, namespace)
}

func (c *ClrkV1alpha1Client) Backends(namespace string) BackendInterface {
	return newBackends(c, namespace)
}

func (c *ClrkV1alpha1Client) CredentialInjectionPolicies(namespace string) CredentialInjectionPolicyInterface {
	return newCredentialInjectionPolicies(c, namespace)
}

func (c *ClrkV1alpha1Client) DaemonAgents(namespace string) DaemonAgentInterface {
	return newDaemonAgents(c, namespace)
}

func (c *ClrkV1alpha1Client) EgressDenyPolicies(namespace string) EgressDenyPolicyInterface {
	return newEgressDenyPolicies(c, namespace)
}

func (c *ClrkV1alpha1Client) EgressGateways(namespace string) EgressGatewayInterface {
	return newEgressGateways(c, namespace)
}

func (c *ClrkV1alpha1Client) EgressL4Routes(namespace string) EgressL4RouteInterface {
	return newEgressL4Routes(c, namespace)
}

func (c *ClrkV1alpha1Client) FallbackRoutingPolicies(namespace string) FallbackRoutingPolicyInterface {
	return newFallbackRoutingPolicies(c, namespace)
}

func (c *ClrkV1alpha1Client) Invocations(namespace string) InvocationInterface {
	return newInvocations(c, namespace)
}

func (c *ClrkV1alpha1Client) LoggingPolicies(namespace string) LoggingPolicyInterface {
	return newLoggingPolicies(c, namespace)
}

func (c *ClrkV1alpha1Client) MCPRoutes(namespace string) MCPRouteInterface {
	return newMCPRoutes(c, namespace)
}

func (c *ClrkV1alpha1Client) RateLimitPolicies(namespace string) RateLimitPolicyInterface {
	return newRateLimitPolicies(c, namespace)
}

func (c *ClrkV1alpha1Client) TaskAgents(namespace string) TaskAgentInterface {
	return newTaskAgents(c, namespace)
}

func (c *ClrkV1alpha1Client) WorkerPools(namespace string) WorkerPoolInterface {
	return newWorkerPools(c, namespace)
}

// NewForConfig creates a new ClrkV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*ClrkV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new ClrkV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*ClrkV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &ClrkV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new ClrkV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *ClrkV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new ClrkV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *ClrkV1alpha1Client {
	return &ClrkV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := clrkv1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *ClrkV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
