/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	scheme "github.com/apoxy-dev/clrk/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EgressGatewaysGetter has a method to return a EgressGatewayInterface.
// A group's client should implement this interface.
type EgressGatewaysGetter interface {
	EgressGateways(namespace string) EgressGatewayInterface
}

// EgressGatewayInterface has methods to work with EgressGateway resources.
type EgressGatewayInterface interface {
	Create(ctx context.Context, egressGateway *clrkv1alpha1.EgressGateway, opts v1.CreateOptions) (*clrkv1alpha1.EgressGateway, error)
	Update(ctx context.Context, egressGateway *clrkv1alpha1.EgressGateway, opts v1.UpdateOptions) (*clrkv1alpha1.EgressGateway, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, egressGateway *clrkv1alpha1.EgressGateway, opts v1.UpdateOptions) (*clrkv1alpha1.EgressGateway, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*clrkv1alpha1.EgressGateway, error)
	List(ctx context.Context, opts v1.ListOptions) (*clrkv1alpha1.EgressGatewayList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *clrkv1alpha1.EgressGateway, err error)
	EgressGatewayExpansion
}

// egressGateways implements EgressGatewayInterface
type egressGateways struct {
	*gentype.ClientWithList[*clrkv1alpha1.EgressGateway, *clrkv1alpha1.EgressGatewayList]
}

// newEgressGateways returns a EgressGateways
func newEgressGateways(c *ClrkV1alpha1Client, namespace string) *egressGateways {
	return &egressGateways{
		gentype.NewClientWithList[*clrkv1alpha1.EgressGateway, *clrkv1alpha1.EgressGatewayList](
			"egressgateways",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *clrkv1alpha1.EgressGateway { return &clrkv1alpha1.EgressGateway{} },
			func() *clrkv1alpha1.EgressGatewayList { return &clrkv1alpha1.EgressGatewayList{} },
		),
	}
}
