/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	scheme "github.com/apoxy-dev/clrk/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EgressL4RoutesGetter has a method to return a EgressL4RouteInterface.
// A group's client should implement this interface.
type EgressL4RoutesGetter interface {
	EgressL4Routes(namespace string) EgressL4RouteInterface
}

// EgressL4RouteInterface has methods to work with EgressL4Route resources.
type EgressL4RouteInterface interface {
	Create(ctx context.Context, egressL4Route *clrkv1alpha1.EgressL4Route, opts v1.CreateOptions) (*clrkv1alpha1.EgressL4Route, error)
	Update(ctx context.Context, egressL4Route *clrkv1alpha1.EgressL4Route, opts v1.UpdateOptions) (*clrkv1alpha1.EgressL4Route, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, egressL4Route *clrkv1alpha1.EgressL4Route, opts v1.UpdateOptions) (*clrkv1alpha1.EgressL4Route, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*clrkv1alpha1.EgressL4Route, error)
	List(ctx context.Context, opts v1.ListOptions) (*clrkv1alpha1.EgressL4RouteList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *clrkv1alpha1.EgressL4Route, err error)
	EgressL4RouteExpansion
}

// egressL4Routes implements EgressL4RouteInterface
type egressL4Routes struct {
	*gentype.ClientWithList[*clrkv1alpha1.EgressL4Route, *clrkv1alpha1.EgressL4RouteList]
}

// newEgressL4Routes returns a EgressL4Routes
func newEgressL4Routes(c *ClrkV1alpha1Client, namespace string) *egressL4Routes {
	return &egressL4Routes{
		gentype.NewClientWithList[*clrkv1alpha1.EgressL4Route, *clrkv1alpha1.EgressL4RouteList](
			"egressl4routes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *clrkv1alpha1.EgressL4Route { return &clrkv1alpha1.EgressL4Route{} },
			func() *clrkv1alpha1.EgressL4RouteList { return &clrkv1alpha1.EgressL4RouteList{} },
		),
	}
}
