/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	scheme "github.com/apoxy-dev/clrk/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// FallbackRoutingPoliciesGetter has a method to return a FallbackRoutingPolicyInterface.
// A group's client should implement this interface.
type FallbackRoutingPoliciesGetter interface {
	FallbackRoutingPolicies(namespace string) FallbackRoutingPolicyInterface
}

// FallbackRoutingPolicyInterface has methods to work with FallbackRoutingPolicy resources.
type FallbackRoutingPolicyInterface interface {
	Create(ctx context.Context, fallbackRoutingPolicy *clrkv1alpha1.FallbackRoutingPolicy, opts v1.CreateOptions) (*clrkv1alpha1.FallbackRoutingPolicy, error)
	Update(ctx context.Context, fallbackRoutingPolicy *clrkv1alpha1.FallbackRoutingPolicy, opts v1.UpdateOptions) (*clrkv1alpha1.FallbackRoutingPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, fallbackRoutingPolicy *clrkv1alpha1.FallbackRoutingPolicy, opts v1.UpdateOptions) (*clrkv1alpha1.FallbackRoutingPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*clrkv1alpha1.FallbackRoutingPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*clrkv1alpha1.FallbackRoutingPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *clrkv1alpha1.FallbackRoutingPolicy, err error)
	FallbackRoutingPolicyExpansion
}

// fallbackRoutingPolicies implements FallbackRoutingPolicyInterface
type fallbackRoutingPolicies struct {
	*gentype.ClientWithList[*clrkv1alpha1.FallbackRoutingPolicy, *clrkv1alpha1.FallbackRoutingPolicyList]
}

// newFallbackRoutingPolicies returns a FallbackRoutingPolicies
func newFallbackRoutingPolicies(c *ClrkV1alpha1Client, namespace string) *fallbackRoutingPolicies {
	return &fallbackRoutingPolicies{
		gentype.NewClientWithList[*clrkv1alpha1.FallbackRoutingPolicy, *clrkv1alpha1.FallbackRoutingPolicyList](
			"fallbackroutingpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *clrkv1alpha1.FallbackRoutingPolicy { return &clrkv1alpha1.FallbackRoutingPolicy{} },
			func() *clrkv1alpha1.FallbackRoutingPolicyList { return &clrkv1alpha1.FallbackRoutingPolicyList{} },
		),
	}
}
