/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	scheme "github.com/apoxy-dev/clrk/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// InvocationsGetter has a method to return a InvocationInterface.
// A group's client should implement this interface.
type InvocationsGetter interface {
	Invocations(namespace string) InvocationInterface
}

// InvocationInterface has methods to work with Invocation resources.
type InvocationInterface interface {
	Create(ctx context.Context, invocation *clrkv1alpha1.Invocation, opts v1.CreateOptions) (*clrkv1alpha1.Invocation, error)
	Update(ctx context.Context, invocation *clrkv1alpha1.Invocation, opts v1.UpdateOptions) (*clrkv1alpha1.Invocation, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, invocation *clrkv1alpha1.Invocation, opts v1.UpdateOptions) (*clrkv1alpha1.Invocation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*clrkv1alpha1.Invocation, error)
	List(ctx context.Context, opts v1.ListOptions) (*clrkv1alpha1.InvocationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *clrkv1alpha1.Invocation, err error)
	InvocationExpansion
}

// invocations implements InvocationInterface
type invocations struct {
	*gentype.ClientWithList[*clrkv1alpha1.Invocation, *clrkv1alpha1.InvocationList]
}

// newInvocations returns a Invocations
func newInvocations(c *ClrkV1alpha1Client, namespace string) *invocations {
	return &invocations{
		gentype.NewClientWithList[*clrkv1alpha1.Invocation, *clrkv1alpha1.InvocationList](
			"invocations",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *clrkv1alpha1.Invocation { return &clrkv1alpha1.Invocation{} },
			func() *clrkv1alpha1.InvocationList { return &clrkv1alpha1.InvocationList{} },
		),
	}
}
