/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	scheme "github.com/apoxy-dev/clrk/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// LoggingPoliciesGetter has a method to return a LoggingPolicyInterface.
// A group's client should implement this interface.
type LoggingPoliciesGetter interface {
	LoggingPolicies(namespace string) LoggingPolicyInterface
}

// LoggingPolicyInterface has methods to work with LoggingPolicy resources.
type LoggingPolicyInterface interface {
	Create(ctx context.Context, loggingPolicy *clrkv1alpha1.LoggingPolicy, opts v1.CreateOptions) (*clrkv1alpha1.LoggingPolicy, error)
	Update(ctx context.Context, loggingPolicy *clrkv1alpha1.LoggingPolicy, opts v1.UpdateOptions) (*clrkv1alpha1.LoggingPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*clrkv1alpha1.LoggingPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*clrkv1alpha1.LoggingPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *clrkv1alpha1.LoggingPolicy, err error)
	LoggingPolicyExpansion
}

// loggingPolicies implements LoggingPolicyInterface
type loggingPolicies struct {
	*gentype.ClientWithList[*clrkv1alpha1.LoggingPolicy, *clrkv1alpha1.LoggingPolicyList]
}

// newLoggingPolicies returns a LoggingPolicies
func newLoggingPolicies(c *ClrkV1alpha1Client, namespace string) *loggingPolicies {
	return &loggingPolicies{
		gentype.NewClientWithList[*clrkv1alpha1.LoggingPolicy, *clrkv1alpha1.LoggingPolicyList](
			"loggingpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *clrkv1alpha1.LoggingPolicy { return &clrkv1alpha1.LoggingPolicy{} },
			func() *clrkv1alpha1.LoggingPolicyList { return &clrkv1alpha1.LoggingPolicyList{} },
		),
	}
}
