/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	clrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	scheme "github.com/apoxy-dev/clrk/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// WorkerPoolsGetter has a method to return a WorkerPoolInterface.
// A group's client should implement this interface.
type WorkerPoolsGetter interface {
	WorkerPools(namespace string) WorkerPoolInterface
}

// WorkerPoolInterface has methods to work with WorkerPool resources.
type WorkerPoolInterface interface {
	Create(ctx context.Context, workerPool *clrkv1alpha1.WorkerPool, opts v1.CreateOptions) (*clrkv1alpha1.WorkerPool, error)
	Update(ctx context.Context, workerPool *clrkv1alpha1.WorkerPool, opts v1.UpdateOptions) (*clrkv1alpha1.WorkerPool, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, workerPool *clrkv1alpha1.WorkerPool, opts v1.UpdateOptions) (*clrkv1alpha1.WorkerPool, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*clrkv1alpha1.WorkerPool, error)
	List(ctx context.Context, opts v1.ListOptions) (*clrkv1alpha1.WorkerPoolList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *clrkv1alpha1.WorkerPool, err error)
	WorkerPoolExpansion
}

// workerPools implements WorkerPoolInterface
type workerPools struct {
	*gentype.ClientWithList[*clrkv1alpha1.WorkerPool, *clrkv1alpha1.WorkerPoolList]
}

// newWorkerPools returns a WorkerPools
func newWorkerPools(c *ClrkV1alpha1Client, namespace string) *workerPools {
	return &workerPools{
		gentype.NewClientWithList[*clrkv1alpha1.WorkerPool, *clrkv1alpha1.WorkerPoolList](
			"workerpools",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *clrkv1alpha1.WorkerPool { return &clrkv1alpha1.WorkerPool{} },
			func() *clrkv1alpha1.WorkerPoolList { return &clrkv1alpha1.WorkerPoolList{} },
		),
	}
}
