//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// Ensure imports are used.
var (
	_ = corev1.EnvVar{}
	_ = apiextensionsv1.JSON{}
	_ = resource.Quantity{}
	_ = metav1.Condition{}
)

// DeepCopyInto is an autogenerated deepcopy function.
func (in *AgentSandbox) DeepCopyInto(out *AgentSandbox) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *AgentSandbox) DeepCopy() *AgentSandbox {
	if in == nil {
		return nil
	}
	out := new(AgentSandbox)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ExecutionResources) DeepCopyInto(out *ExecutionResources) {
	*out = *in
	out.CPU = in.CPU.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
	if in.EphemeralStorage != nil {
		in, out := &in.EphemeralStorage, &out.EphemeralStorage
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ExecutionResources) DeepCopy() *ExecutionResources {
	if in == nil {
		return nil
	}
	out := new(ExecutionResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *AgentEgressRef) DeepCopyInto(out *AgentEgressRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *AgentEgressRef) DeepCopy() *AgentEgressRef {
	if in == nil {
		return nil
	}
	out := new(AgentEgressRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *AgentState) DeepCopyInto(out *AgentState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *AgentState) DeepCopy() *AgentState {
	if in == nil {
		return nil
	}
	out := new(AgentState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *AgentStreaming) DeepCopyInto(out *AgentStreaming) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *AgentStreaming) DeepCopy() *AgentStreaming {
	if in == nil {
		return nil
	}
	out := new(AgentStreaming)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *AgentIdentity) DeepCopyInto(out *AgentIdentity) {
	*out = *in
	if in.Extractors != nil {
		in, out := &in.Extractors, &out.Extractors
		*out = make([]IdentityExtractor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *AgentIdentity) DeepCopy() *AgentIdentity {
	if in == nil {
		return nil
	}
	out := new(AgentIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *IdentityExtractor) DeepCopyInto(out *IdentityExtractor) {
	*out = *in
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = new(HeaderExtractor)
		**out = **in
	}
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(BodyExtractor)
		**out = **in
	}
	if in.JWT != nil {
		in, out := &in.JWT, &out.JWT
		*out = new(JWTExtractor)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *IdentityExtractor) DeepCopy() *IdentityExtractor {
	if in == nil {
		return nil
	}
	out := new(IdentityExtractor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *HeaderExtractor) DeepCopyInto(out *HeaderExtractor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *HeaderExtractor) DeepCopy() *HeaderExtractor {
	if in == nil {
		return nil
	}
	out := new(HeaderExtractor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *BodyExtractor) DeepCopyInto(out *BodyExtractor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *BodyExtractor) DeepCopy() *BodyExtractor {
	if in == nil {
		return nil
	}
	out := new(BodyExtractor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *JWTExtractor) DeepCopyInto(out *JWTExtractor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *JWTExtractor) DeepCopy() *JWTExtractor {
	if in == nil {
		return nil
	}
	out := new(JWTExtractor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *TaskAgent) DeepCopyInto(out *TaskAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *TaskAgent) DeepCopy() *TaskAgent {
	if in == nil {
		return nil
	}
	out := new(TaskAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *TaskAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *TaskAgentSpec) DeepCopyInto(out *TaskAgentSpec) {
	*out = *in
	in.Sandbox.DeepCopyInto(&out.Sandbox)
	in.Resources.DeepCopyInto(&out.Resources)
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.MaxConcurrent != nil {
		in, out := &in.MaxConcurrent, &out.MaxConcurrent
		*out = new(int32)
		**out = **in
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
	if in.ScheduleInput != nil {
		in, out := &in.ScheduleInput, &out.ScheduleInput
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.EgressRefs != nil {
		in, out := &in.EgressRefs, &out.EgressRefs
		*out = make([]AgentEgressRef, len(*in))
		copy(*out, *in)
	}
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(AgentIdentity)
		(*in).DeepCopyInto(*out)
	}
	if in.Streaming != nil {
		in, out := &in.Streaming, &out.Streaming
		*out = new(AgentStreaming)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(AgentState)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *TaskAgentSpec) DeepCopy() *TaskAgentSpec {
	if in == nil {
		return nil
	}
	out := new(TaskAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *TaskAgentStatus) DeepCopyInto(out *TaskAgentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *TaskAgentStatus) DeepCopy() *TaskAgentStatus {
	if in == nil {
		return nil
	}
	out := new(TaskAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *TaskAgentList) DeepCopyInto(out *TaskAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TaskAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *TaskAgentList) DeepCopy() *TaskAgentList {
	if in == nil {
		return nil
	}
	out := new(TaskAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *TaskAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DaemonAgent) DeepCopyInto(out *DaemonAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DaemonAgent) DeepCopy() *DaemonAgent {
	if in == nil {
		return nil
	}
	out := new(DaemonAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *DaemonAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DaemonAgentSpec) DeepCopyInto(out *DaemonAgentSpec) {
	*out = *in
	in.Sandbox.DeepCopyInto(&out.Sandbox)
	in.Resources.DeepCopyInto(&out.Resources)
	if in.MaxRestarts != nil {
		in, out := &in.MaxRestarts, &out.MaxRestarts
		*out = new(int32)
		**out = **in
	}
	if in.MaxLifetimeSeconds != nil {
		in, out := &in.MaxLifetimeSeconds, &out.MaxLifetimeSeconds
		*out = new(int32)
		**out = **in
	}
	if in.EgressRefs != nil {
		in, out := &in.EgressRefs, &out.EgressRefs
		*out = make([]AgentEgressRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DaemonAgentSpec) DeepCopy() *DaemonAgentSpec {
	if in == nil {
		return nil
	}
	out := new(DaemonAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DaemonAgentStatus) DeepCopyInto(out *DaemonAgentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UpSince != nil {
		in, out := &in.UpSince, &out.UpSince
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DaemonAgentStatus) DeepCopy() *DaemonAgentStatus {
	if in == nil {
		return nil
	}
	out := new(DaemonAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DaemonAgentList) DeepCopyInto(out *DaemonAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DaemonAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DaemonAgentList) DeepCopy() *DaemonAgentList {
	if in == nil {
		return nil
	}
	out := new(DaemonAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *DaemonAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *WorkerPool) DeepCopyInto(out *WorkerPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *WorkerPool) DeepCopy() *WorkerPool {
	if in == nil {
		return nil
	}
	out := new(WorkerPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *WorkerPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *WorkerPoolSpec) DeepCopyInto(out *WorkerPoolSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.PodTemplate.DeepCopyInto(&out.PodTemplate)
	if in.MaxExecutionsPerWorker != nil {
		in, out := &in.MaxExecutionsPerWorker, &out.MaxExecutionsPerWorker
		*out = new(int32)
		**out = **in
	}
	if in.WarmPool != nil {
		in, out := &in.WarmPool, &out.WarmPool
		*out = new(int32)
		**out = **in
	}
	if in.ImageCache != nil {
		in, out := &in.ImageCache, &out.ImageCache
		*out = new(ImageCacheConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *WorkerPoolSpec) DeepCopy() *WorkerPoolSpec {
	if in == nil {
		return nil
	}
	out := new(WorkerPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ImageCacheConfig) DeepCopyInto(out *ImageCacheConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ImageCacheConfig) DeepCopy() *ImageCacheConfig {
	if in == nil {
		return nil
	}
	out := new(ImageCacheConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *WorkerPoolStatus) DeepCopyInto(out *WorkerPoolStatus) {
	*out = *in
	out.Capacity = in.Capacity
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *WorkerPoolStatus) DeepCopy() *WorkerPoolStatus {
	if in == nil {
		return nil
	}
	out := new(WorkerPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *WorkerPoolCapacity) DeepCopyInto(out *WorkerPoolCapacity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *WorkerPoolCapacity) DeepCopy() *WorkerPoolCapacity {
	if in == nil {
		return nil
	}
	out := new(WorkerPoolCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *WorkerPoolList) DeepCopyInto(out *WorkerPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkerPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *WorkerPoolList) DeepCopy() *WorkerPoolList {
	if in == nil {
		return nil
	}
	out := new(WorkerPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *WorkerPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
