/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiclrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	internalinterfaces "github.com/apoxy-dev/clrk/client/informers/internalinterfaces"
	clrkv1alpha1 "github.com/apoxy-dev/clrk/client/listers/clrk/v1alpha1"
	versioned "github.com/apoxy-dev/clrk/client/versioned"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EgressL4RouteInformer provides access to a shared informer and lister for
// EgressL4Routes.
type EgressL4RouteInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() clrkv1alpha1.EgressL4RouteLister
}

type egressL4RouteInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEgressL4RouteInformer constructs a new informer for EgressL4Route type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEgressL4RouteInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEgressL4RouteInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEgressL4RouteInformer constructs a new informer for EgressL4Route type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEgressL4RouteInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClrkV1alpha1().EgressL4Routes(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClrkV1alpha1().EgressL4Routes(namespace).Watch(context.TODO(), options)
			},
		},
		&apiclrkv1alpha1.EgressL4Route{},
		resyncPeriod,
		indexers,
	)
}

func (f *egressL4RouteInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEgressL4RouteInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *egressL4RouteInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiclrkv1alpha1.EgressL4Route{}, f.defaultInformer)
}

func (f *egressL4RouteInformer) Lister() clrkv1alpha1.EgressL4RouteLister {
	return clrkv1alpha1.NewEgressL4RouteLister(f.Informer().GetIndexer())
}
