/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/apoxy-dev/clrk/client/informers/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// AIProviderRoutes returns a AIProviderRouteInformer.
	AIProviderRoutes() AIProviderRouteInformer
	// AgentSandboxRevisions returns a AgentSandboxRevisionInformer.
	AgentSandboxRevisions() AgentSandboxRevisionInformer
	// Backends returns a BackendInformer.
	Backends() BackendInformer
	// CredentialInjectionPolicies returns a CredentialInjectionPolicyInformer.
	CredentialInjectionPolicies() CredentialInjectionPolicyInformer
	// DaemonAgents returns a DaemonAgentInformer.
	DaemonAgents() DaemonAgentInformer
	// EgressDenyPolicies returns a EgressDenyPolicyInformer.
	EgressDenyPolicies() EgressDenyPolicyInformer
	// EgressGateways returns a EgressGatewayInformer.
	EgressGateways() EgressGatewayInformer
	// EgressL4Routes returns a EgressL4RouteInformer.
	EgressL4Routes() EgressL4RouteInformer
	// Invocations returns a InvocationInformer.
	Invocations() InvocationInformer
	// LoggingPolicies returns a LoggingPolicyInformer.
	LoggingPolicies() LoggingPolicyInformer
	// MCPRoutes returns a MCPRouteInformer.
	MCPRoutes() MCPRouteInformer
	// RateLimitPolicies returns a RateLimitPolicyInformer.
	RateLimitPolicies() RateLimitPolicyInformer
	// TaskAgents returns a TaskAgentInformer.
	TaskAgents() TaskAgentInformer
	// WorkerPools returns a WorkerPoolInformer.
	WorkerPools() WorkerPoolInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// AIProviderRoutes returns a AIProviderRouteInformer.
func (v *version) AIProviderRoutes() AIProviderRouteInformer {
	return &aIProviderRouteInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// AgentSandboxRevisions returns a AgentSandboxRevisionInformer.
func (v *version) AgentSandboxRevisions() AgentSandboxRevisionInformer {
	return &agentSandboxRevisionInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Backends returns a BackendInformer.
func (v *version) Backends() BackendInformer {
	return &backendInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// CredentialInjectionPolicies returns a CredentialInjectionPolicyInformer.
func (v *version) CredentialInjectionPolicies() CredentialInjectionPolicyInformer {
	return &credentialInjectionPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DaemonAgents returns a DaemonAgentInformer.
func (v *version) DaemonAgents() DaemonAgentInformer {
	return &daemonAgentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// EgressDenyPolicies returns a EgressDenyPolicyInformer.
func (v *version) EgressDenyPolicies() EgressDenyPolicyInformer {
	return &egressDenyPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// EgressGateways returns a EgressGatewayInformer.
func (v *version) EgressGateways() EgressGatewayInformer {
	return &egressGatewayInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// EgressL4Routes returns a EgressL4RouteInformer.
func (v *version) EgressL4Routes() EgressL4RouteInformer {
	return &egressL4RouteInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Invocations returns a InvocationInformer.
func (v *version) Invocations() InvocationInformer {
	return &invocationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// LoggingPolicies returns a LoggingPolicyInformer.
func (v *version) LoggingPolicies() LoggingPolicyInformer {
	return &loggingPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// MCPRoutes returns a MCPRouteInformer.
func (v *version) MCPRoutes() MCPRouteInformer {
	return &mCPRouteInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RateLimitPolicies returns a RateLimitPolicyInformer.
func (v *version) RateLimitPolicies() RateLimitPolicyInformer {
	return &rateLimitPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// TaskAgents returns a TaskAgentInformer.
func (v *version) TaskAgents() TaskAgentInformer {
	return &taskAgentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// WorkerPools returns a WorkerPoolInformer.
func (v *version) WorkerPools() WorkerPoolInformer {
	return &workerPoolInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
