/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/apoxy-dev/clrk/client/informers/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// AIProviderRoutes returns a AIProviderRouteInformer.
	AIProviderRoutes() AIProviderRouteInformer
	// AgentSandboxRevisions returns a AgentSandboxRevisionInformer.
	AgentSandboxRevisions() AgentSandboxRevisionInformer
	// CredentialInjectionPolicies returns a CredentialInjectionPolicyInformer.
	CredentialInjectionPolicies() CredentialInjectionPolicyInformer
	// DaemonAgents returns a DaemonAgentInformer.
	DaemonAgents() DaemonAgentInformer
	// EgressDenyPolicies returns a EgressDenyPolicyInformer.
	EgressDenyPolicies() EgressDenyPolicyInformer
	// EgressGateways returns a EgressGatewayInformer.
	EgressGateways() EgressGatewayInformer
	// EgressL4Routes returns a EgressL4RouteInformer.
	EgressL4Routes() EgressL4RouteInformer
	// LoggingPolicies returns a LoggingPolicyInformer.
	LoggingPolicies() LoggingPolicyInformer
	// MCPRoutes returns a MCPRouteInformer.
	MCPRoutes() MCPRouteInformer
	// RateLimitPolicies returns a RateLimitPolicyInformer.
	RateLimitPolicies() RateLimitPolicyInformer
	// TaskAgents returns a TaskAgentInformer.
	TaskAgents() TaskAgentInformer
	// WorkerPools returns a WorkerPoolInformer.
	WorkerPools() WorkerPoolInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// AIProviderRoutes returns a AIProviderRouteInformer.
func (v *version) AIProviderRoutes() AIProviderRouteInformer {
	return &aIProviderRouteInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// AgentSandboxRevisions returns a AgentSandboxRevisionInformer.
func (v *version) AgentSandboxRevisions() AgentSandboxRevisionInformer {
	return &agentSandboxRevisionInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// CredentialInjectionPolicies returns a CredentialInjectionPolicyInformer.
func (v *version) CredentialInjectionPolicies() CredentialInjectionPolicyInformer {
	return &credentialInjectionPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DaemonAgents returns a DaemonAgentInformer.
func (v *version) DaemonAgents() DaemonAgentInformer {
	return &daemonAgentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// EgressDenyPolicies returns a EgressDenyPolicyInformer.
func (v *version) EgressDenyPolicies() EgressDenyPolicyInformer {
	return &egressDenyPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// EgressGateways returns a EgressGatewayInformer.
func (v *version) EgressGateways() EgressGatewayInformer {
	return &egressGatewayInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// EgressL4Routes returns a EgressL4RouteInformer.
func (v *version) EgressL4Routes() EgressL4RouteInformer {
	return &egressL4RouteInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// LoggingPolicies returns a LoggingPolicyInformer.
func (v *version) LoggingPolicies() LoggingPolicyInformer {
	return &loggingPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// MCPRoutes returns a MCPRouteInformer.
func (v *version) MCPRoutes() MCPRouteInformer {
	return &mCPRouteInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RateLimitPolicies returns a RateLimitPolicyInformer.
func (v *version) RateLimitPolicies() RateLimitPolicyInformer {
	return &rateLimitPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// TaskAgents returns a TaskAgentInformer.
func (v *version) TaskAgents() TaskAgentInformer {
	return &taskAgentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// WorkerPools returns a WorkerPoolInformer.
func (v *version) WorkerPools() WorkerPoolInformer {
	return &workerPoolInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
