/*
Copyright 2026 Apoxy, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiclrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	internalinterfaces "github.com/apoxy-dev/clrk/client/informers/internalinterfaces"
	clrkv1alpha1 "github.com/apoxy-dev/clrk/client/listers/clrk/v1alpha1"
	versioned "github.com/apoxy-dev/clrk/client/versioned"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MCPRouteInformer provides access to a shared informer and lister for
// MCPRoutes.
type MCPRouteInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() clrkv1alpha1.MCPRouteLister
}

type mCPRouteInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMCPRouteInformer constructs a new informer for MCPRoute type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMCPRouteInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMCPRouteInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMCPRouteInformer constructs a new informer for MCPRoute type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMCPRouteInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClrkV1alpha1().MCPRoutes(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClrkV1alpha1().MCPRoutes(namespace).Watch(context.TODO(), options)
			},
		},
		&apiclrkv1alpha1.MCPRoute{},
		resyncPeriod,
		indexers,
	)
}

func (f *mCPRouteInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMCPRouteInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *mCPRouteInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiclrkv1alpha1.MCPRoute{}, f.defaultInformer)
}

func (f *mCPRouteInformer) Lister() clrkv1alpha1.MCPRouteLister {
	return clrkv1alpha1.NewMCPRouteLister(f.Informer().GetIndexer())
}
