/*
Copyright 2026 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiclrkv1alpha1 "github.com/apoxy-dev/clrk/api/clrk/v1alpha1"
	internalinterfaces "github.com/apoxy-dev/clrk/client/informers/internalinterfaces"
	clrkv1alpha1 "github.com/apoxy-dev/clrk/client/listers/clrk/v1alpha1"
	versioned "github.com/apoxy-dev/clrk/client/versioned"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TaskAgentInformer provides access to a shared informer and lister for
// TaskAgents.
type TaskAgentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() clrkv1alpha1.TaskAgentLister
}

type taskAgentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTaskAgentInformer constructs a new informer for TaskAgent type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTaskAgentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTaskAgentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTaskAgentInformer constructs a new informer for TaskAgent type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTaskAgentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClrkV1alpha1().TaskAgents(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClrkV1alpha1().TaskAgents(namespace).Watch(context.TODO(), options)
			},
		},
		&apiclrkv1alpha1.TaskAgent{},
		resyncPeriod,
		indexers,
	)
}

func (f *taskAgentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTaskAgentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *taskAgentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiclrkv1alpha1.TaskAgent{}, f.defaultInformer)
}

func (f *taskAgentInformer) Lister() clrkv1alpha1.TaskAgentLister {
	return clrkv1alpha1.NewTaskAgentLister(f.Informer().GetIndexer())
}
