import { createRouter } from '@tanstack/react-router'
// Generated by the TanStack Router Vite plugin on dev/build (gitignored).
import { routeTree } from './routeTree.gen'

export const router = createRouter({ routeTree })

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}
